// We require the Hardhat Runtime Environment explicitly here. This is optional
// but useful for running the script in a standalone fashion through node <script>.
//
// When running the script with npx hardhat run <script> you'll find the Hardhat
// Runtime Environment's members available in the global scope.
const { ContractFactory, ethers } = require("hardhat");
const hre = require("hardhat");

async function main() {
  // Hardhat always runs the compile task when running scripts with its command
  // line interface.
  //
  // If this script is run directly using node you may want to call compile
  // manually to make sure everything is compiled
  // await hre.run('compile');

  //deploy ERC20 WOLF Token, then Traits, Woolf and Barn in that order

  const FaithToken = await hre.ethers.getContractFactory("FAITH");
  const faithToken = await FaithToken.deploy();
  await faithToken.deployed();
  console.log("Faith Token deployed to:", faithToken.address);

  const Traits = await hre.ethers.getContractFactory("Traits");
  const traits = await Traits.deploy();
  await traits.deployed();
  console.log("Traits deployed to:", traits.address);

  const God = await hre.ethers.getContractFactory("God");
  //need to pass wool token address, traits address and max token
  const god = await God.deploy(faithToken.address, traits.address, 5000);
  await god.deployed();
  console.log("God NFT deployed to:", god.address);

  const Temple = await hre.ethers.getContractFactory("Temple");
  //need to pass woolf and wool token addresses
  const temple = await Temple.deploy(god.address, faithToken.address);
  await temple.deployed();
  console.log("Temple deployed to:", temple.address);

  // which index to upload traits to
  const indexTrait = [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 12, 14, 15];
  // the length of each individual traitType
  const traitLen = [
    [0, 1, 2, 3],
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
    [0, 1, 2, 3, 4, 5, 6, 7],
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    [0, 1, 2],
    [0, 1, 2, 3, 4],
    [0, 1, 2, 3, 4],
    [0, 1, 2],
    [0, 1, 2, 3, 4, 5, 6],
    [0, 1, 2, 3],
    [0, 1, 2, 3, 4],
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    [0, 1, 2, 3, 4, 5, 6, 7],
  ];
  // array for traits encoded
  const encodedTraits = [
    //0
    [
      [
        "Black",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAACtklEQVRoBe1YMU4dMRD1opRJgSggBUUk6IP0r0DJLThWbpGSK3wJepBSUEAKRJH0m/+M3+qtZe/3zIooimwJjT2e8Ty/8dj7CaG3zkBnoDPQGegMdAY6A52BzkBn4D9mYFixt9Hg647jdRw3Z58jvq9fTqK8+/EcHl9+hdOjT0F1mNw+PEG4YnmcxuvLiwBABILotUa7bze3MDHHO6gtvKRn0CUbzmETsPc2F0AEaw3aalfbgBsgzltLa7WrreUGeLU5r60507fazZxk4AYoa7xr1wXQkjacQYt9vlsXQKQNgfcVAOfXpNl8L6Udxldk6T4EOFwx6f6DmyuWy0nSEF+U0oUNgGteEMZwpZjOlExlbUz935BI7fR3fPhx6u/e5hFjSNroPHVWkJYUz9JJ1pheOWsBZxMtt/m+vQ8/X39jqjmuKcUEgwjpfKEbG0DxjzpItfNUswkgA+fMUJ9LbgjMeZsF4MA0MrAGJWhKnSNznk+uD7qQp18CRF1pI9YYqwHmIPKxFVBub0lx9CU7+UIYL815z2FzuSdAuOOmht8lZEzBqU6rODmaYlpSHH+LEB0LhmOAAkiCox6S9yL6Oz9sshmkKcUAoEwhIBv1lNRTLvnSpiQtDA67dMUUl77vlhiUFwQYmtmDsYnBtPiQniv4T43MUU4Tu448byZwWMPCoMZEoFHPm/ZpCF0qEjMwruF2BEAu0iDdcbwMRkxanVCgsku6hg1UTVYB5KpSBHiv8V0Y+P7SxiutRcI4szsR/zDSpuPEqOU46FLmKp6cS9U6TUqn1U5cZl0vg/G3LoNnlYr7MgbBfOnOnCHYM/BUVy1dulaLzR5ob9PWIpmdPSwBlsiYRtQPCeqt7zD8LAAjOFSsFgGDlySPAOaQahSMFaSmpRRDdbW00UbXstjSv8vOwD/JwB9ARSSp6yEcvwAAAABJRU5ErkJggg==",
      ],
      [
        "White",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAC80lEQVRoBe2YzY0UMRCFu9nNgQMCiQMciIJNghCQyGKzQCIEklii4AAHkBCHzYGl8Wf6jV57+8flQQIhlzTjdrl+np9dds8MQ5fOQGegM9AZ6Ax0BjoDnYHOQGfgP2ZgPGNuU8C3OU+r4/Tjw3XGNz56MTxIT3ffPw7fPt0Oj58/HC6S7mfSTUmHXL68pmnK1eI03X1+n5MD5EgAziQunr1qAsnkwwIzJK0R7MRkjX1p0wSQILVJa+1KYOo3A2S/1Uit3VasZoBPrq62Yi70tXYLJ+s0AyQGlbonR+N7vhprAhhZNvZgxF7A1DYBZNlIzGeLJT8Hz1nmlnOQyeVbZErnIefc2nko/fj7/MOnKVcTg3OyUcmdRZ7Vn8cB1gQu+eVbivYs0VILGP2/JSzt6fPl3ZvTc7qbJ/q0svFx6aLAI9TnFwTtN/YYor6WGx17Eylt6EdfHEJ7kHtVyzgnykD4ApQ+J2V6cLva+9v9QwBxxKFkxgtDE8BW7MoeXVQiAEdemQAgJhyYCsMLRmDFfMsr12V0Rtj7rATM40iniWAvsG5X8xwG6ODy8/xeKDYB5TYCsabT2F4b9iv3kzMDcwroegCUfnugfCxyzODHGXcSfpesFYLrvIpnx1DOyBJPOt9I5OcefUDBksChkxR+TLIapFZEsXZbAGwtlfRqy0B7vqWt9yMMjmm58hKnK8xj5Oc9Br/e3AxPX7+VTzV7OIQYTPYEHy0ZMbKIObXS08722df1Nc8RBj0eySadcwys7T0bD7FWJvJ+5HlR0QeOzQBbGcx4vDo597jK+NfB901Z7QcTuTfsse4N1iooAt2ztPT/lLQCXJyJ/GHk4v2Z5ch28FCL1VgMHHXWqnXNp9ZuzRddK4P5t66Sz9eZCoHzMudj/JzfxARR0Byw8mtruTxWjU1VumgVL/YeGWBJjHlGf5GQPlU0wH0iGtpsIwAzOCrUi2AzchrQFsCGpaZgoiAjs9laNmH0WBFb+fe2M/BPMvALccI1g3rNsnYAAAAASUVORK5CYII=",
      ],
      [
        "Tan",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAACvElEQVRoBe1YO07EMBBNEA1INJyBei9ARUtDsRUSp6BHCNFzCiSqLWhoqbjA1pyBBgnKkGf5RWOv7fVMACFkS2js+T6/iZ0NXddGY6Ax0BhoDDQGGgONgcZAY6Ax8I8Z6GfsbVDEmutYA4en63OH72Rx5OTz+rV7e//oDg/2O6mD8fTmAcJUyxI0fK6uOgAiEFTPDfrtLW/hoq63k0tc0rNoyYc2bAL+1mECiGK1RWv9chswA8TzVjNq/XK5zACXx4tczkBf6xcEiYUZoMjxo1MTQE3b8Axq/OPdmgCibSi87QDQPqfN6nvJ79C9RUr3IcDhivH3H8JMtUwM+mK9KO5xh0JcziZwyGYFGCBhK6mM19T/hkRrp7/7y7NpPr6bB6wh6SPt1GlBaqh3PxD4/iVLXMt249nEiH2w1v5wULWYYFDcF8LUDYDiH3WQ0k/GS5/SXAWQiWJmqI8lAdE/ttesNQCnU8vCsgBBUEob/cWplubifLdorTCmAFFHYBVpsi6zAcYg4nW2cqVB02KXkuyk8lttqVzUaa4ZxOCOmwa+S8iYBCd18hT7QFVNTYvdtwjRyXsPOoACSIKjHyTvRczHOGyyGqSqxQAgmUJBDuopqacsxdInJTUM9mO7XIvHV9hGrhKDq5d1d3H3yJhq9hCgYnD0R/JeFEMON8gcJfWQ3t/FSn3NXLWbKGHwTEa2aWm5nKfgcTILoEy0ZW6uo3kGNzDI0wkj2ErpNgIVCu0zmEyNQ8BWQmL9XcMKMHj+8A8jOeTaMxpc8NJ329wKMHsfxgVTpzr2Ka3NAPGty+L+dcaDgPvS1YR9zjcxkjBpaROxLdcumavGJ86bXGtPcfDsISNYImOygvwhQf14gABcboSmrNQAdOBwQuUhyGYeDXwE4INW48BoQWp2k2sbMcpcGl/GN9kY+JMMfAHFxRmC4LXBggAAAABJRU5ErkJggg==",
      ],
      [
        "Dark Tan",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAACwElEQVRoBe1YO07FMBDMQ/SIloqGEiFR0nIDRMUZOAENouEEnIEKcQNaSiRESUNFizhByBhPNA52nncfIIRsCa293s9k1uu80HVtNAYaA42BxkBjoDHQGGgMNAYaA/+YgcUKz9YbfN15vI79zdlhwLeztRHk8+t79/Ty1u1ub3aqw+bx5R2EK5fHqX+8OuoAiECQvTRot3d6CxNzvrVS4Dk9k87ZcA8PAXvvcAFEstqktXalB3ADxHmrGbV2pVhugEcH26WYib7WLnGShRugxPjRqQugpWw4gxb76dO6AKJsSLysAbi/SpnN91J8wvAWmbsPAQ5XTLz/4ObK5WIwJltI8og7FXI5u8AhmhdggoSlpHK6pv43JEo7/p2f7I/z4d3cYw1JG92nzgrSQn34gcD3L1niWsuNs4kxtcHa+sPBVGKCQfKYCNMwAIp/1EGqnfqrzdzcBJCBpsxQP5UERPvpfs3aAnDsWibWBARBqXu0l67W7dn5+uxuxWYOEHUEVhGmaLIywCmI6bqYuXLDUuIQkuzk4nv3crGos1wz8MEdNw58l5AxBac67eLoaMppKXH4FiE6vfegAyiAJDjaQfJexHzww0NWgzSVGACUKSTkoJ6Seso5X9rkpIXBxVCuUOLhFfYl1hyDt/cv3cX1A32q2YODicHBHsEXkgwxwiBzlNRDRvvgq/qauYVBjYdkvZ43ndNQdCbW6A/pdhx8k47WoJm5O4+XwYBBuxMKdHZOlwFcrbKewWxgNAHfs5BYf9fwAkzuRPzDSIeuI6OW46ChzF08Oue6ddyUSa2duCRTL4PhW5fJ4+uMjYD7MiTB/irfxAjCoAnqJYtSuTRWjc2SNJ/b1i5Ozh5CgCUyphn1hwT11vcw/CwAAzh0qDYBk+ckjwD2UGo0jBWkliWXQ3WlstFGY1ls6d9kY+BPMvAB2zob0Oc9jgIAAAAASUVORK5CYII=",
      ],
    ],
    //1
    [
      [
        "White Cap",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAlklEQVRoBe3UwQqFIBAFUHv//5d+R8yrRRAxCWpQi+PGaGS8nLRSDAIECBAgQIBAQ2Bp1HpKkSx+pPcvadz7KmqtZY0o53lrkoXu7T29fg8Xx7g+vx0yDfeVkGm4r0jehrvqnQOPfu4nLsn0QW41GPkVzNzOkf1a+dUIECBAgAABAgQIECBAgAABAgQIECBAgAABAqMCf3uxtA5v9cejAAAAAElFTkSuQmCC",
      ],
      [
        "Grey Cap",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAtElEQVRoBe3SwQ2AIBBEUbQSGqD/QmiATtAx0WCCGneJFz8HRUEY3xICDQEEEEAAAQQQuBGYbsbeDNXO5CFrj1ikppRCjDGUUo57zlmZ3evPnT9/8+oI136ksAq9tp5sO/Wx7wl4CtfqaddRIa0l6IbbOfawelbfU26L4GU4hVGTXtv3lNsScAvx1cVSYs/Bt+z3lQX7IIAAAggggAACCCCAAAIIIIAAAggggAACCCCAwL8EFs3LMrGK+w9lAAAAAElFTkSuQmCC",
      ],
      [
        "Yellow Cap",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAuElEQVRoBe3TTQ5AMBBA4dE7OYSFM4kzSTiEK4mf0UgqKUmnjY1nU1Talw8iHAgggAACCCCAwItA9TKXMrVFHi6ytossnHprG3ony+gkHI9FYtGpa0tu4BnX1Pd99VpjS0TmBN7ipllEw3TUo1Sk9TuJxvk0H3mpanDbrTpl2ssi+BgX6oXnOa/bEnhBfTJa2HP+Tst+n0CwCQIIIIAAAggggAACCCCAAAIIIIAAAggggAACCPxOYAeArC5MOu0QeAAAAABJRU5ErkJggg==",
      ],
      [
        "Brown Cap",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAuElEQVRoBe3SQQ5AMBCF4WFr7xQO5IgO5BT21mUklUqKdKax8XdBabXPNxWhIYAAAggggAACDwLNw1jJUMhMrrJ2jUXCODTSdyLLKud9mo/M7vXbzJ+XvDrDpR9pWA29t5xsOvW17wl4CZfq6a61QlpLkA0XOWJYfda+p9wWwdtwGkZbPI+x7ym3JeAR4quLpcSeg2/Z7ysL9kEAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAIF/CWwd7yepPNHeVQAAAABJRU5ErkJggg==",
      ],
      [
        "Green Cap",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAuklEQVRoBe3S7w1AMBCH4WMMie2sYAor2E5iDH9O0qaSIu4aX7z9QGm1P89VhIYAAggggAACCNwIVDdjb4bWzOQia5dYZO3HWtpGZJol3odu0czu9evMn795FcOlH2lYDb23nGw69bHvCXgKl+rprqVCWkuQDRc4Qlh91r6n3BbBy3AaRls4j6HvKbcl4BHiq4ulxJ6Db9nvKwv2QQABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAgX8JbBWzK1WuSw5fAAAAAElFTkSuQmCC",
      ],
      [
        "Blue Cap",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAv0lEQVRoBe3SMRJAMBCF4XADpUbvAK7jcK7jAHqN0hGwZmJiJhi7GY0/BSGRPN/GORoCCCCAAAIIIHAjkN2MvRlaIpOTrJ1ikaWqW1eUjZun/riPQyeZzevnkT9/8+oIF34kYSX01mKy4dTHviXgKVyoJ7umCqktQTSc5/Bh5Vn6lnJrBC/DSRhp/jz6vqXcmoB7iK8umhJbDr5mv68s2AcBBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQT+JbACfxgzYQTfwjQAAAAASUVORK5CYII=",
      ],
      [
        "Purple Cap",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAu0lEQVRoBe3S0Q2AIAxFUXQiF2ABp3A0p3ABFmAjtSYYTBBjS/zx8qEoCM9TnKMhgAACCCCAAAIVga4y9mZoLUxusnaLRVbvJzcMo4txOe8hzJLZvH5f+PM3r85w+UcSVkLvrSSbT33sWwJewuV6smurkNoSFMMljhRWnqVvKbdG8DachJGWzmPqW8qtCXiE+OqiKbHl4Gv2+8qCfRBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQOBfAhtp2jXLmOhOAgAAAABJRU5ErkJggg==",
      ],
      [
        "Red Cap",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAvElEQVRoBe3S4Q1AMBCG4WIFW5jCUKYwlClsYYUGJ6lUUhV3jT/e/qC02s9zdY6GAAIIIIAAAghkBKrM2JuhNTG5yNolFlnHpndd07rZL+d98JNkNq9fJ/78zaszXPyRhJXQe0vJxlMf+5aAl3CxnuxaKqS2BMlwgSOElWfpW8qtEbwNJ2GkhfMY+pZyawIeIb66aEpsOfia/b6yYB8EEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBD4l8AG35oz6W8DzHYAAAAASUVORK5CYII=",
      ],
      [
        "Long Hair Black",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAA80lEQVRoBe2V0Q2EIBBE9SqxAUuhWkqhATvhHOIZNRHZ1cSPe3wohB129onQdTQIQAACEIAABCAAgX8m0N8oPhu07jxeYQ4h7PxN07SOh2FY++rEGPVy5fKIijkZOhqRi2P7xXlNWg3uyCl5Sul0jXEc87YIj8nPsWLLeDZXDb+ar4qXSbfBRhr9Etfi5ZGYrM82r2T5g5XYq+vMBLWnZpOmahW/3YsWsdmgZfEnYjF4lyIEXyFoPYBrt81VAafXVEWoM61MtyRezk1didKY83n2YO8g6DJXKPCAAAQgAAEIQAACEIAABCAAAQhAAAIQeI3AF+vdQP35x1MOAAAAAElFTkSuQmCC",
      ],
      [
        "Long Hair Blonde",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAA/klEQVRoBe2VTQ6CMBBGW+NVWHgVL+NZvIxXccFVjJVBGqmBhm9K4sLHBmjn55vXZiYEHghAAAIQgAAEIACBfyYQG4pPgq87j9cxPW6HQl/ff/R2XRn2eH6abblYeK//eJxGcSboW8hSmmznFakKLMhZ8tMlrca4X2OaF+ERWZ7TEoLK2iCushtMfHV/y6Zb4EYacbLbomUXm2THNkRS0Xj9gkzQ7tQgUqrW7Od3UXGWBSrB97BFYCtFCLYSVP1tknjaTPD6af3iXY71tPGrNuZy5VPfzFNFzue5g1EdYZO9LC4XyRsCEIAABCAAAQhAAAIQgAAEIAABCEDgNwReXihCp+J5OowAAAAASUVORK5CYII=",
      ],
      [
        "Long Hair Brown",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAA+UlEQVRoBe2VsRHCMAxFbYagZh2mYAIq5qBiAqZgHWqWcCKfucRc4khK7lLwVKSI9K2vF8cOgYAABCAAAQhAAAIQ+GcCccXwyaB19/EK0/1SS9+fwe/pWOduz5yrXyqn84iyOTH0a2Sq57fOa9JqsCInzR+vMLvG9RzSeAiPycPU1Np3vblmLOWb4pJ0G1TSiKVO42WTmiSfrV9p+CN0y3p1wUxQ9lRv0hRSP96LFrHZoGXxLWoxuJYiBHchaD2AW7fN0gCz11RDKGdaDk3jcm7KlShh7ufZg9FB0GUuj8QDAhCAAAQgAAEIQAACEIAABCAAAQhAYDcCHTvJN0E6mWemAAAAAElFTkSuQmCC",
      ],
      [
        "Long Hair Ginger",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAA/ElEQVRoBe2VwRHCIBBFwVYcO/FkJx6sxoOdeLITx1qQRZgExyC7ZMaDby8JyX7280JY5wgIQAACEIAABCAAgX8m4AcWHxRacx2rMNxPtb3bYxrvt9O93O3OaWyqZRElc2Lo3Uht6zUqeVaTWoMVOSl+vLrFOS4HF+aLsJjcfFp177Norhnf3jfF+aXZYCcNn/N6vKySE+SzxZk0f7AUtuqcmqDsqWhSFZI/34sasdqgZvI1cjE4ShGCowS1eukklmPGWXWLbarhXM60FK02V/T53JSWKKGuZ9mDXtvCrObKIrlCAAIQgAAEIAABCEAAAhCAAAQgAAEI/IbAEzZWMt+q/h9qAAAAAElFTkSuQmCC",
      ],
      [
        "Long Hair White",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABBUlEQVRoBe2VWxLCIAxFi+Myyv4X1u4DCdOgdKaSwNQfTz8k1DwuxxCXhQcCEIAABCAAAQhA4J8JhInDJ0fscJ3RwJSfRt++73W/rmu1xQihlBmt1eSybERc2ratrL0P9cuJ2xNZKg34NHqk+LccKk6DRkR6sUutqsnw03n9a241Hmp4V4M4SZndvAxaJW6BchmM4rRSEfl5ifSLO9bSTr3eOxfWXszv3/1xdrrYuwle5LntNQJn0UJwlqA3vtziHOS+jcfEdsc9nQplpsn/sISlGGN3CutIcs7OKmukB0MWVhNYjMO/exhLLnwgAAEIQAACEIAABCAAAQhAAAIQgAAEfkfgBVc+kXLWJxa6AAAAAElFTkSuQmCC",
      ],
      [
        "Regular Black",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAvklEQVRoBe3T0Q2EIBBFUdZsITRAKVRLKTRAJ6xjIlGSBWeMX15+hADD4wSdoyGAAAIIIIAAAgi8WeBz4/JVsdd8jnVjjTGe8pVS2th73/rSSSnJx3SWZdMWTgL1QSRF3/Z11pDfvuDVsYSTw3POfy8ZQqhXLjE6cxlNzuZG4WTvbH5W3zy/vj/ND+K064/BbgkeCz3VNwWUt6dp2vWa2qxFAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQOApgR8APidu61UCEQAAAABJRU5ErkJggg==",
      ],
      [
        "Regular Blonde",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAyElEQVRoBe3TwQ2DMAyFYUCswqGrsExnYRlW6YFVUEONhIirkDoGTv05QeI4Lx9QVVwIIIAAAggggAAC/yxQnzh8KFjr3se7MMxjo/JN056363Tbtn9LrR5Uq48fPIvWcBLoO0hqm63OG7JNNbWMSTjZ/PEMh4d8DXWwHCK3n35PucrEXC6clP+aT7S8Zujz/e0fnKFlaX3c8pRg3Oiue1fA+I+1BCutt/SkBgEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQACBuwUWzxMnWbWd9LwAAAAASUVORK5CYII=",
      ],
      [
        "Regular Brown",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAyUlEQVRoBe3TsQ2DMBCF4QvKDKmzDlNkAqrMQZUJMkXWoWYJB1tC2BGxz4dc8VMhznd+/mREeBBAAAEEEEAAAQTOLHA5cHhX0Wvex9roxkfaOs1b3vstrT3foZZ+VJ7O0hTC+UC/Qfb2XNdZQ173hmq++XB+89dH/h5y6MVpDpHbr8sVS7VcON9bqpfmm+vL/dsunGJK7fp45CHBeFCrd1PA+I/VBKtdr5nJGgQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEWgt8AQ+YJEXYrZCYAAAAAElFTkSuQmCC",
      ],
      [
        "Regular Ginger",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAxklEQVRoBe3TvQ2DMBCG4QtiE5RNqLIJBdNQZBOqbIKYxeFACIMS/xyi4qWyubP9+RGI8CCAAAIIIIAAAgjcWeBx4vIuY635HOtCN7T7eJ9xm9fVNtbRs5vnprMsi+ZwGugYZB9rma191pDlr01T3mk4Pbzp5e8l3y9xKZcInVeEirFaKJyujdVj+5vr0/eX84NIbr8f7JSgv9FVY1NA/49NCZbbn7InPQgggAACCCCAAAIIIIAAAggggAACCCCAAAIIXC3wBRWJHHVuQSeQAAAAAElFTkSuQmCC",
      ],
      [
        "Regular White",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAsklEQVRoBe3T2w2AIAxAUXAO9l8M9kAglsAPjxqNiZcPhdjScojGMBBAAAEEEEAAAQT+LGBvHD5u5KrraBNjGl1/IYS6ds7VeZ5YW8poa3V7rSxyc9F7X96zh8SljfsTrVRSxtSecvHRHtJcTtA2qGG/6pWrm+ZL8KvXLEVHeu233fg292gXX5yrGmz/2JVD7cav7EkMAggggAACCCCAAAIIIIAAAggggAACCCCAAAJPC5xIcGu46usxBwAAAABJRU5ErkJggg==",
      ],
      [
        "Laurel",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAk0lEQVRoBe3QSw2DQBAA0Nn6QAEO6qAGKoH0UhWYINhBQxVUyDQLJ0Ig2Wvz9jQ7k/nkRXgECBAgQIAAAQIECBDYC4xLyWEqWbMt8TDF2rOfdv0r1+Vj9fGO7Pqt7fvJaInnVzbvux1POM9Urftz21GXtcbnk1UIECBAgAABAgQIECBAgAABAgQIECBAgACB/xP4AdyRNnr6KYXPAAAAAElFTkSuQmCC",
      ],
    ],
    //2
    [
      [
        "Blue Toga",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABNklEQVRoBe2WPRIBMRiGQ2UVtBp6lTO4iBs4jRu4iAOoVHqa7cwo0DGvmXdkM9ldvojGmybJ5kvy7JOfXeeUZEAGZEAGZEAGZEAGZEAGZEAGZEAGZEAGZEAG/tVAx/Lis/nqfj0f3e1SusN+XTvGZLq49/ojVwzGbrdZ1sY1MXSbGpvaMCkmB0QszoeLtb/7zAQIe0iEjE1Gc2hjfCyu7ZkJEEvrp9BiWA/j/b5tZRMg9h2t0CKhwqVFXNM+bQM0bVwOisPCMvJTuX3uS0AzWQ8H+5sMsrOfx+D8dmv5K4C54PBSyYA54ZIBc8MlA/p3HQbLkZKWuBi+TmsOOIyZBOgql0wexDTAPEyVUQVY0WGoJBnk95jzttUZ90luBuTPAScDHP5aQsgwjvHKZUAGZEAGZOA3Bh7Fq1hvQOEl/wAAAABJRU5ErkJggg==",
      ],
      [
        "Brown Toga",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABMklEQVRoBe2WPQrCQBBGJ2JnKQhewAPYeCsP44VsbGw8gKWNoFhar3wJA5uw2SQzLgh+U2T/JuPL2yxRhEEDNEADNEADNEADNEADNEADNEADNEADNEADNPCvBirLg+93VXi8Ra6vIJe79NbYriVslpWsFiKHc+jNyzHMc4u5Nfyo1GwhpCBjuFydobXZUEJqHfYQDWTTT111XfNTOUNzJkBsrQa2ELZ0jFbt6Vycr3NjWxMgtlStwFIMqXCxvdQrMBbQ9OJqcRwW7aM93UINq3CYsx4O3IswGWxubV9TcO0M2+grgKXg8EhuwJJwbsDScG5A/UqgUKlwbXF8Wn8SsBRUXNdlMC5Uqk9Ar1mXQf0eK8TQWPOmtGbA7j8YwB2fK+lCdvOmwDGXBmiABmiABvwGPkF2SdMSjkE8AAAAAElFTkSuQmCC",
      ],
      [
        "Green Toga",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABKElEQVRoBe2WsQ3CMBBFLxFTIKVmFyZgCjqmoGMKJqClYwfqSIyB4UecdHISJznjBr4bO/jbeXm2Q0RYaIAGaIAGaIAGaIAGaIAGaIAGaIAGaIAGaIAG/tVA5Xnw06UO7UOkvQc5H8PoHLtDFZpNJc1aZL99juZSDHWqM9WHm+LmgBjKWbih/rm/reYGbQ72OsA3pAjE9BnVHBLIe4vLIJbWlthifB3n7diptgsQ+06txEsdLy1yqX06BejauDopDou2Ud+uoduXgNbiPRw63mVQB9t6CM72e9tfASwFh4fKBiwJlw1YGi4b0L7rMFmJkrXE9rSWgMOcWYCloOy8BLQ2PO3fNqj/x2pm6lpzS2q3wd4Xy+cDNoaMc0vgmKUBGqABGqCBfAMvOmZPwg0UbFkAAAAASUVORK5CYII=",
      ],
      [
        "Grey Toga",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABH0lEQVRoBe2WQQ6DIBBFadMz6NYLuPUWXtytF3Crl6AZ0290QiAw4qL5bhDnA68PtTrHgwZogAZogAZogAZogAZogAZogAZogAZogAZogAYyDIzj6Pu+923b+tgwqUtO8rFcrPaJFWO1rutQ9uu6vtBBK3BN07hTDqWs9p2V/oWXZdnPZHGBCB1nOORDudS1IsBt2y7z6q3WfZ2/DE50igBlS2EFFgGlt1ZyoVsgwXWUiwBl9DzPx30nkMMwOA2nc8eqGSfFgHqNaZr2+9H6UOh5bwGsBSewZsCacGbA2nBmwPO7TiarcZi2+O4HIvQDTYChCe++RkCr0f82iP9jWEr1kctpiw3i4wCLCZx8tWhInUOeLQ3QAA3QAA08Y+ALh7BT1owWSdIAAAAASUVORK5CYII=",
      ],
      [
        "Purple Toga",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABLElEQVRoBe2WsQ3CMBBFDTNABQU1O2QNahbINCxAzQAskAVSUVNABTsEfaQvnSwngTOmgO/GTnw+vzzbSUJQkQEZkAEZkAEZkAEZkAEZkAEZkAEZkAEZkAEZ+FcDE8+D1/Whu1xP4X47h6bZ9+aoqm03m6/CcrEOu92mN26IYTrUOdSHSTE5IFJxFi7V/+o9FyDsoRAyNRnNoY/xqbixey5ALK0tscX4Oo63Y8faLkDsO1qhRULFS4u4oX06BujauEyKw8I26rY9PvcloFm8h4PjXQY52NYpONvvbX8EsBQcHiobsCRcNmBpuGxA+65DshIla4ntaS0Bh5xZgKWgbF4BWhue9m8b5PeYZsauGfdO7TbInwNOBjj8tcSQcRzjVcuADMiADMjAdww8ANzwWPxAA60bAAAAAElFTkSuQmCC",
      ],
      [
        "Red Toga",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABKUlEQVRoBe2WQQ7CIBBFRxeewFPYeBH3HsCTeYDuvYjReAhP4Kb2m/yUEAo6iBs/SQMtw/D6AK2ZigzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIgAzIwL8aWHhe/GT74WJ3u47X0c6zOQ62HTa2tm68dtbPxuUYlrnOXB8mxeSASMWFcKn+d5+5AGEPhZCpyWgOfYxPxZWeuQCxtGGJLcb3cXw4ttR2AWLf0QotEipeWsTl9mkJ0LVxmRSHhW3Uvd1e+xLQLN7DwfEugxwc1im4sN/b/gpgKzi8VDVgS7hqwNZw1YDhbx2StShVS9ytptPaAg45qwDt0QprylsHOOVp1hJgrdoqg/w/JkTpnnGf1G5AfhxwMsDhqyWGjOMYr1oGZEAGZEAGfmPgCUd+QCq8o50QAAAAAElFTkSuQmCC",
      ],
      [
        "White Toga",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAA9klEQVRoBe2WzQ6DIBAGsVff/wl5AC56tn4mGtwgUH8bM3togN2FcYimzhEYwAAGMIABDGAAAxjAAAYwgAEMYAADGMAABn4wMIzRdd3gvR9ybcqrTpGrOz03nTj+5CBjuNsBZys6WOOUgZqaVJ9d+9iFmnkIYSlr29bZq7bzuH5pvHpgDc1Q9mq3DF/NN+2vK47Dwil3C8jWISW4vwFMmZvhtx7ulnVB5OAeN1iCexwwfpMFk4qjV9kc2UBApf5mjFJNLr/rQ53b8OwcgEeNvttg3/crQaX5qrhystugvoHxGYLTvxYLaeviHsYYwAAGMICB6w18Af9hely0N1tNAAAAAElFTkSuQmCC",
      ],
      [
        "Yellow Toga",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABJklEQVRoBe2WwQ3CMAxFHViEAbh2CBAMwRicECfYggE4gliCKwMwCUEuitRaqRvs5vZzS/1Tv74EFCIMGIABGIABGIABGIABGIABGIABGIABGIABGIABGPjDQHxQvB1DPO1C1JZxnXOc13JabaYVtdqmibRcEA1B8nOuc84zTID3Z2h7JsgcQBcu5XO5sWcmwNe7/1ppUc5lvr9an/1U6Jlslc9W2j42xBD7Swxya7m2PURzH/NCppaH/3wN7blM4JwJa3L1MG0xN5YjByczlvkkgLXg+IPcgDXh3IC14dyA3f86flmN4driVeP6gRZ9jwtwTp+iJp6QC9DTuHQtAEtNDeVcBuUtZWw+BKE9NwPKG0u6MEhImdNgUIMBGIABGICB6Q18AfxlVUmvphGEAAAAAElFTkSuQmCC",
      ],
    ],
    //3
    [
      [
        "Angry Blue Eyes",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAdklEQVRoBe3QSwqAMAwFwOp9vf+ygm6KbQgBXTldvnwapjWPAAECBAgQIECAAAECBD4T6MnmrJ6Mv1OOjojy0q97qXvVfFx3PI/p7c5XE6VsK3XPzeNh464onzdICBAgQIAAAQIECBAgQIAAAQIECBAgQOCvAidsbQrWUHFs/AAAAABJRU5ErkJggg==",
      ],
      [
        "Angry Green Eyes",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAd0lEQVRoBe3QSw6AIAwFQPSgHtPrYYgbIpCmia4clq8fminFI0CAAAECBAgQIECAAIHPBGqwOaoH4++UV0es8tSve6p71nweLX0eU8udzyZS2ZbqHpv7w/pdq3zcICFAgAABAgQIECBAgAABAgQIECBAgACBvwpcou8KJlmAYz4AAAAASUVORK5CYII=",
      ],
      [
        "Angry White Eyes",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAdklEQVRoBe3QSw6AIAwFQPT+d67GFSGUT6Irh+Xrh2ZK8QgQIECAAAECBAgQIEDgM4GYbJ7VJ+PvlLMjsnzr13Oru9Mc8dzRHnPHbdQZXoiOhZ5RS31FvSvLR7vUCBAgQIAAAQIECBAgQIAAAQIECBAgQOBfAhdkcQ34gvJelgAAAABJRU5ErkJggg==",
      ],
      [
        "Eyepatch and Blue Eye",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAeElEQVRoBe3QQQqAIBBA0an7dv9lURAMQgtRZIgntFBSvy/CIECAAAECBAgQIECAwH8EzspPKRl3R71fizcleG9PnTY/nr7hyG0wKAfks77WB6/r254j+nYu+Lt03IL3u4IAAQIECBAgQIAAAQIECBAgQIAAAQIRF0hgDGcIesnHAAAAAElFTkSuQmCC",
      ],
      [
        "Eyepatch and Green Eye",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAeklEQVRoBe3QQQrAIAwEwLQP7TP7vRYPQhB6EEWkjOBB0WQzERYBAgQIECBAgAABAgT+I/DsPMqW4Uqoulu8KYHPtuq0832VUsMhj8FAOUCu9XU/2K7vew7R93PB663DLZhfCwIECBAgQIAAAQIECBAgQIAAAQIECES8Z8EMDxgLPmMAAAAASUVORK5CYII=",
      ],
      [
        "Eyepatch and White Eye",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAd0lEQVRoBe3QUQqAIBBAwa3733mjIBChD1kRiRH6UFKfE2EQIECAAAECBAgQIEDgPwK581O2jLuj3q/HmxJ89qfOmmc+feXIoxjUBrRnfa0Xrxvb3kaM7Vzw99ZxC97vCgIECBAgQIAAAQIECBAgQIAAAQIECERcMZYN+BCp+rUAAAAASUVORK5CYII=",
      ],
      [
        "Bloodshot Eyes",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAcElEQVRoBe3QMQ6AIBAEwNPC/3/O92iMDUE2wZqhY7N3galyCBAgQIAAAQIECBAgQGBtgSt8P+WhPo73cTyfnnU85c9jUj6/+W1ufwe6fvuwdlfKu3FXAgQIECBAgAABAgQIECBAgAABAgQIEFhY4AYiWwe2n6YRuwAAAABJRU5ErkJggg==",
      ],
      [
        "Closed Eyes",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAUklEQVRoBe3QMQ4AQAQEQP7/6NNuo7rSqESWxFQpAgQIECBAgAABAgQIECBwV6A/X3+xn7e2ecS1BAgQIECAAAECBAgQIECAAAECBAgQIHBcYADu3AICWssZmQAAAABJRU5ErkJggg==",
      ],
      [
        "Regular Blue Eyes",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAbElEQVRoBe3QMQ7AIAwDQNr/9v8jVTshwENmjg3LROFacwgQIECAAAECBAgQIEDgbIEevp/yUN/H9z4upM+/x7pMygujv+pV7M/1cbFxVsrn9+4ECBAgQIAAAQIECBAgQIAAAQIECBAgcK7ACyQTCNipBvr5AAAAAElFTkSuQmCC",
      ],
      [
        "Regular Green Eyes",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAeklEQVRoBe3QQQrAIAwEwLQP7TP7vRYPQhB6EEWkjOBB0WQzERYBAgQIECBAgAABAgT+I/DsPMqW4Uqoulu8KYHPtuq0832VUsMhj8FAOUCu9XU/2K7vew7R93PB663DLZhfCwIECBAgQIAAAQIECBAgQIAAAQIECES8Z8EMDxgLPmMAAAAASUVORK5CYII=",
      ],
      [
        "Regylar White Eyes",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAbElEQVRoBe3QQQrAIAwEQNv//zmF9iLqgj073lySkExrHgECBAgQIECAAAECBAicLVDh/JSH8nV8r+P9tOrdY1om5fuTv8rrb8NQ3y/Wz0r50O5LgAABAgQIECBAgAABAgQIECBAgAABAgcLPBwXC/pOTWTeAAAAAElFTkSuQmCC",
      ],
      [
        "X Eyes",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAXklEQVRoBe3QIRIAIAwDQf7/aTCcxIJgMZnGtOwYHgECBAgQIECAAAECBAj8KzD318skmsv6J3k64tRfPbIjypY3l/WSAAECBAgQIECAAAECBAgQIECAAAECBAgksADfhgn3lI5CEgAAAABJRU5ErkJggg==",
      ],
      [
        "Cyclops",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAcklEQVRoBe3QMQrAIBBFwTX3v7MJQdTGIvCrMFYL4mOdKocAAQIECBAgQIAAAQIEjgLtePP9om9PYt1UqD9n7tfam420r1kNDGOxQGklIr8cuUVYleyubU0ECBAgQIAAAQIECBAgQIAAAQIECBAg8CeBG+0vBglsQTukAAAAAElFTkSuQmCC",
      ],
      [
        "Goggles",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAh0lEQVRoBe3RsQnDMBQEUBkCrgwuU7jzGp4gc2SltAbPpkFs+CMcwbh4KnRqvk48tWYRIECAAAECBAgQIECAwF8FzvC2aO51Z1nSlT6wuvp7rVw+W+WwH+3Xe53Haar8znNlug3hYPJdaVf4RGMECBAgQIAAAQIECBAgQIAAAQIECBAg8HCBCxILCgfTR+qbAAAAAElFTkSuQmCC",
      ],
      [
        "Glasses Blue",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAfklEQVRoBe3QMQ6AIAwFUPS+3n+s1hDCYEysk+axUEhKP681iwABAgQIECBAgAABAgS+K7AUo8fRl725z+vurjRrnV9/UI8gEdGWbeQ8i4u7UrjMU27snxnJ+nkE7+fc3s6YnlISIECAAAECBAgQIECAAAECBAgQIECAwI8Edjt4EdgZsLGGAAAAAElFTkSuQmCC",
      ],
      [
        "Glasses Green",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAeklEQVRoBe3QwQ2AIAwFUHQjF3JM16tixHAgRnszeVxKmrR8XikOAQIECBAgQIAAAQIECPxXYEpGj2Ouztban6de6q253/7hfgeJiLJsaxs9Aw96qXB1aXrwSvRWsH1AJUCAAAECBAgQIECAAAECBAgQIECAAAECTWAHECERiI2Fhu8AAAAASUVORK5CYII=",
      ],
      [
        "Glasses White",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAdklEQVRoBe3Q0QqAIAwFUOv//9laDFGQoL0Fxxd1OL2e1gwCBAgQIECAAAECBAgQ+K/AUYze777ojXkeb7XSW+d8+4f1CNL7kvHZbGqlcJGn3JifWdLlfbtaHjcRIECAAAECBAgQIECAAAECBAgQIECAAIEhcAHC9A7+rLxf1gAAAABJRU5ErkJggg==",
      ],
    ],

    //4
    [
      [
        "Regular",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAATElEQVRoBe3QwQ0AAAgCMeL+O+sSPHyUAS6kiREgQIAAAQIECBAgQIAAAQIEvghs+8i0g3oECBAgQIAAAQIECBAgQIAAAQIECBBoCRxNZwECvih2QQAAAABJRU5ErkJggg==",
      ],
      [
        "Wide",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAW0lEQVRoBe3QsQoAIAgFQPv/j641XHQQgjg38aFyEYoAAQIECBAgQIAAAQIECBAg8Fpgpwdyn8b9dvWjZfJ+anJveViAAAECBAgQIECAAAECBAgQIECAAIE/BQ6s7wMA8IsSrAAAAABJRU5ErkJggg==",
      ],
      [
        "Angled",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAWUlEQVRoBe3QMQoAMAgDQPv/R7drhk7i5jmJkCBXZQgQIECAAAECBAgQIECAAAECXYHTDX5yN26TvVE7s+ajM41aCBAgQIAAAQIECBAgQIAAAQIECBBYKfAArAwCAak4E58AAAAASUVORK5CYII=",
      ],
    ],

    //5
    [
      [
        "Ginger",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAA/klEQVRoBe2SQQ7CIBBFp8aTmHgTd57Ehadx4Unc9SYmvQoyFFpE2hQwxsVjURhm+PP7QIQBAQhAAAIQgAAEIAABCEAAAhCAAAR+SuB5FVPSsLQ+1t7FQcn6fu42mdxat9R7v5RY2Tf90MnpYCSQOd6kS+vVmNaIha31dtbgoy49l8bFB7yAsQacSY1HA+/So7kxd3k42FW9qg4Fk5agG2rQmpi0Znoilq6OKeeigk/NFWflw3Vrsh+yJVWb1X/mu5lAMde9lZ5qthpUDffA9E2G4d+chvNmSBbOzQJRP2fUx9/UjVqwhAAEIAABCEAAAhCAAAQgAAEIQOCvCLwA4iY3Ighs/aMAAAAASUVORK5CYII=",
      ],
      [
        "Blond",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAA5ElEQVRoBe3SbQ7CIAyAYTC7iolexct4ll3Gq7hkh0Hb0IwtkgA1xh8vf8ZHaesjITAQQAABBBBAAAEEEEAAAQQQQACBnwqkR0g9BXvjy9ynctEzf86xqcnWuFrtkQbTssZwOacgMrUGZF/OJU7i36PpBx0b1ZvHzYa1NKZNSmxuYHdNGrOz613no7V2eXsWKvRJ0fTy2xuSs0Ymm3i/uRlNs6zebNt9L7soVke86ZGrhuty7kz/QnmTNvKbk+W2aYedX3eCol751r6ZtyjBFAEEEEAAAQQQQAABBBBAAAEE/krgBTWRRIDafH3UAAAAAElFTkSuQmCC",
      ],
      [
        "Salt and Pepper",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAA7UlEQVRoBe2U4Q2DIBBGbdNBWIBRnJZRXMBNKB/B5mirEWgaf7xLjHdw3H08xGnCIAABCEAAAhCAAAQgAAEIQAACEIDAXwnM8xxbGrbm29p3G7T43vtTIs/m7fV+7E0cjMd1XSfnnJ7sL8tye8+XMOXIlJ9MG/rI08SRNS8oxWISIIE5LAKqPnYubUBzXb16COZmqemLkAYsRXusI+JUt1eg1lZmL8I3olVyQ9CF3dSPSZgJazeEoIGhHkOLi5x8m/VNblaOVeFw/eECm6j0tr+dX9Y1LXAhAAEIQAACEIAABCAAAQhAAAIQuBSBJ5MbOMISYhZYAAAAAElFTkSuQmCC",
      ],
      [
        "Brown",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAA+0lEQVRoBe2UyxHCIBCGkbEGz7ZjFanAk3XkZAVWYTueLSLIImFWJRkejuPh2wuv5d+fLxBjCAhAAAIQgAAEIAABCEAAAhCAAAQg8FMC42BdTcHafK1t9aCmfzyYIpOleUu1t0sLK/Pudp/MfmfNODxNni7T5j1fjEmOhOT7kAN95MnCWlRviGLOGwgmZRwNvNTR5s7XsNRUq2lTdOL83QpdMehNJC1Nz9OVnLQW9xY3LZ84K64fQo5odlPBZPPJonaimKvVS080ew2KRnjNcifniHdOht363QKzKd/q3843dVUJuhCAAAQgAAEIQAACEIAABCAAAQj8FYEH3m40u+q3bK8AAAAASUVORK5CYII=",
      ],
      [
        "White",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAzklEQVRoBe3SSQ7DIAxAUeg54P4Hg3ukGOHIIqnKEFVdfDbMtvOCczQEEEAAAQQQQAABBBBAAAEEEEDgpwJHaTMJZ8/b2C87mRmnlIaKHD03k/vb2UOS2nZ3we63Ioc+qI/l+4XBuRTpQgj1eM75cs3uxRhlfzXXJfbowonU/0YrXIItyWkRy29QA2h/VlsGuvZEv8sudX2sw/safivH1uVWWa1Q3qS29uZkuh1/O4AWVXpL+WRck4IhAggggAACCCCAAAIIIIAAAgj8lcAb9WNoufUvwiIAAAAASUVORK5CYII=",
      ],
    ],

    //6
    [
      [
        "Straight",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAUElEQVRoBe3QsQkAAAgDQd1/aG0zgI1wVlZPuCpHgAABAgQIECBAgAABAgQIECBA4KtAHw6faF12I+slQIAAAQIECBAgQIAAAQIECBAgEAILy5wBAhOUg1kAAAAASUVORK5CYII=",
      ],
      [
        "Sad",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAXUlEQVRoBe3QMQoAMAgEMPv/R7d0k4LL0TFOKnhIqhQBAgQIECBAgAABAgQIECBAgACBQWAN+2S929HP3Babt/25m/LOebJLAgQIECBAgAABAgQIECBAgAABApPAAWZbAwAaTlyaAAAAAElFTkSuQmCC",
      ],
      [
        "Tongue",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAaUlEQVRoBe3QsQkAIRAEQLX/SizA6gSfNz4DRYzGcGHPZVLyCBAgQIAAAQIECBAgQIAAAQIECCwE8iLfjUdQuHK7BIdPon/MHNRbPek/7USaTwf4jAABAgQIECBAgAABAgQIECBA4I7AB1mDBGEWCWqPAAAAAElFTkSuQmCC",
      ],
      [
        "Open",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAbklEQVRoBe3QwQnAIAwFUF2vAzikA3S9iCDSi5eS9vRyCoF8kleKIkCAAAECBAgQIECAAAECBAgQIHAQqIf5m3E8ltJys4Ii7r7vq1ebfUp2Ssi67BPB/bWGAAECBAgQIECAAAECBAgQIEDgd4EB0x8GBIGDrCUAAAAASUVORK5CYII=",
      ],
      [
        "Smile",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAWklEQVRoBe3QMQ4AIAgEMPz/o3U1LDDgZNkIFyCNUAQIECBAgAABAgQIECBAgAABAgQeC+y0P/dp3G9XP1om76cm95aHBQgQIECAAAECBAgQIECAAAECBD4VOAWHAwCFcooMAAAAAElFTkSuQmCC",
      ],
    ],

    //7
    [
      [
        "Bare Feet",
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=",
      ],
      [
        "Sandals",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAiElEQVRoBe3QMQqDQBAF0Jk6peARrNLnKp4ih/FWuUKOEEhpPUHSiIoiWL6tdpm/f+BFOAQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAtcI9PesM01n8/PunD+O7s9H1meMeH8ruiajvf1/DK9a9UzZabrMb2WP9poTILAj8APuWhUKt7cB1QAAAABJRU5ErkJggg==",
      ],
      [
        "Basic Shoes",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAlUlEQVRoBe3QsQ3AIAxEUWcJaFmAmimYlimoWYAWliAKEhSxoiipP5VlDmM9EQ4CCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIICAEjhU56URYxwrUmudZSlFzfHez5xzbsUlpaRy+/Kh+PTgWi7nLNbaPa61Jr13NccYM+65EMKvJfdnFAggoAVOSMEcA2C0l9IAAAAASUVORK5CYII=",
      ],
    ],

    //9
    [
      [
        "White",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAADC0lEQVRoBe1YPW4WMRDdRTQ0IKUgBRKEIgGl4wZcgDYSF+AKtGk5AXfgEklPQYcINFFQChokaKiixW/s8c7659sZb9LZ0hfb8/v8xl5bGYbeOgOdgc5AZ6Az0BnoDHQGOgOdgc5AZ6DKwFjV1BVTXbWqMeezOkzTj08exfXXGc2T43nMo4J+PDyB1pTzPsdT94XERV8GDXv8eF40rgvv1VUrmpAwsJIZR3kjMA5oBnjx6r33DUxO0zREMBzV9Sy/CXYXj98IrX5oBsihL7//ImDjmG8pAGb5T2e3peXR16NN3/78G158+aDbV45BsP7y0QNENudrZrC0jlKpS3YWWTPAz8/e+tO5K5tjj+x22azozJS7eFRijvv39xUPs/7h3tMoay2x/Tvo9pFLRrcJ9iIagAQANIecgQt5Cxn2TUsI5j+RTQACUO5h0sraHH4YmvegC6K9k7V2ElccWwEiGf2m89Phxt3LooQxKAaQQw8716IfJpZmAUgPhZCQcsAZjweA4QPB+xFyGRzz8NAwMao9JHPQwt2KxKP/EBPwACQnKlx7uaIu0QD0T6w0eAK0CkrauTEt5vBkXrDHVj3hsgr1ZUCDRA5k9bbgBXCfRCM/ocNWqS5K+OoBOqfx9Slcl6tFUpEYBjRPZc4v+JOJ9o+mxHXWkEWWsDRPkHAF8Bo6SHSlqYpBlEKeXgqUMsRz7jnbcg72qQLP333kirBlsVcBRMmwYtHycjGT3Afj4rbwIBksARaxF0Ndif3eWzhmEzAVDlJW9sxYL9AA3LnCmIqZ4z4qtg10Jdbk4L3GvcZHYbMNoATDzHGP5FKvAFMy2QZQgilFX9OXfBKZbn8lTmGaXldlKy9tzqM5JNXE6VWFj3BJVg2gUGwrsUgQboiRbwqh2jRsBTj/E2klfWDUsh0WEVsBLoLc5eRWAHJ5A9BbLXPL6aqVS8bS2KiIt57ifO+5j3HpnUevn+Q76JgGcLmQVZAWgATu8uxsODjaXw1MBuImwWsIB8YK0rKaWtkYrIxlsWX/3t8JA/8BbjDv+PB7z/EAAAAASUVORK5CYII=",
      ],
      [
        "Black",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAC/ElEQVRoBe1WwU4WMRDuEi8molEvEIiJxoNXwjPwFFx9Jy5ceQNuXHgACBxJNJoYjVzUgCYc136lX5ndbdmZLtza5P+nOzOd+frN7LbOtdEYaAw0BhoDjYHGQGOgMdAYaAw0BhoDRQa6oqVs6MumWYs5n3VB/3FnK6A4+3qZ0Gy9XUtzTnL2/aMzmE05VxjQIpkcwHLgEEva6G/JQV8zQCYjsMgK4yVJPf24LjkoJ2aAB6dfQmgm7PveEYzMSf15bAWukz6auRkgg/749TcA67ppSwEw9d+935IxjT4frb+4unG72++K/SdDgGmw9+HFU6jN+aoZlCA4z5WatlpZDXDv6NixD0vJYYffkmGm3CcLJWbS69/fOJ3I56/eJF1tiZ+kCPpJ55OF0wS9iAEgEUB4hp7Ahb6GDHvTBgR3f4lNAAJQSrjUsnYX3rnqHvRBtGey1k/iSnMrQCQLv+336w7nsihhCooJ9LDDz4+0Dg+WYQEYLgoxYcpBkHwh2I+8VNARz1FnYlT7kqSgOFtPP/9k3iAJksoxOOrnPkv0k1IDMDA3Ds5LAIOVQMkNYY6f/6CnDcf1xTdcXWIEBsjSacENUBI4JdZJGzY0bhf6SqkGiEWxtIPdIqlMDL+czqu7cWvAd24MkhWcc+VIN+vCmoE6so5cKdbay2du8/WqO7nt5yIOFYO5cuRYA6qSPiIGkADm8s8/goumvFABRFLc/8SYlAs9ikFJ31xbeBuBUtJ9IlUAkQQ7vm+QOcr7fC02zWcmlGQuKJmjnPPX2lUMaoKROUrNGo3PIoASDJmjRHJp14DJ+SwCKMHkgs/Zc2vGOlV/jRfF5/RNK9ilujqP5iWRiQbz8fmLD3JON1hkfFhUYpmLp0WU0rRoXgtQfdRFRi3tMNhQLcBBkMd8eBCALG8E2j1kmWverlK5ZCyNj4p461s86T18jHP3PFxGx99BzyyAy43MgrQADOAOTz65DX+P0wx5kuA2hBfGCtKym1LZiFXGsvhyfZOPwsB/HEofnUVokuYAAAAASUVORK5CYII=",
      ],
      [
        "Tan",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAC+klEQVRoBe1XMW4VMRD1IpqPBEgRNQWioOIOSFRpUyFRII5AiYQApc8R0lKloKGlygVSpYiQ4ACRAImUyz7j58z3etgZ709nS8nYnvHM85uxvT+E3joDnYHOQGegM9AZ6Ax0BjoDnYHOQGdAZWBQNbpi1FWLGnc874Lx6uRdRPH17CKjefb0ce6zU9NvDg6hdsW8RYceyeAAVgMHX1JHe08M2jYBJADIxAr9Zcl5bQPZcKHjBvj9+dvokqyM41gFyXnacd0CnpnaDZAeLn//icCGYV5SYI/zsFvT5t6XvY3nP6/Ct6PXav1JF2Dw0Zvj8OT+BtPueM0MShDss+443oVsBvjg1YfA+tKAQA+7Nc1N+RQspphBf13+YHcm7+09zHOtKb6dPdg7wxQsviaoRTQASQDiGPMELuZbyPAXbURw/S+zCUAASgmTVtau3YfQXIOTE+ubbLWTuHLfCxDB4t+X9y8C3mWRwuwUHcxDD7up5XUYeJoHYPxQSAFzDILkgWA98qOChhinORej1kOSndbeVgTe/LuII54SHEEuXUu0k9ICMDJXOi+BaqCkHfpxMweHecMJjHrCzSmGc4DUXgtugFKygD7WSR1ruLQrx2aAWLj/8RPE1m4RVAaGQW0O69J6mJibJcUqa4giU1gbl0iYAXzllBsrbTE2MYi6KU9v6ZxjSgYrxmA/ZuDl0WdmhKZVuZWuqsV0hwEcdgynU+Oa/PtEWRenE2Nc8z/Tqs7EIGongas6wSSZolQNnQpLDZp2z1qkdOJQzU0MqquFgsxRCtWq7iqAEgyZowQqqW9FuQqgBFMDsKSvrSnnTPVVLkrj8rlSzOJ0cxzLIVEDl+8vrpTanOrAoFiVYumf9x1fCqlb028FaLqkASwx6imHrf20AtxycpODnQBkehPQYZdpbjldWrqkL4uNiXjvKZ7VHi7j2ncePjDKe3BiFsDlRhZBegBGcCenZ2Hv7p1FxzCQLwm+hnBgvCA9u9HSRrDSl8eW67u8EQb+AnBqEeAgxB71AAAAAElFTkSuQmCC",
      ],
      [
        "Dark Tan",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAC9ElEQVRoBe1YIW8WQRC9a0hITUuQiAZDUkHDj8BWESwSV98EhyHBN/0HRZGqWiwOQYogwQAC2bQ1ldd7m33b+fZ2uJm9r25XdPZmZmfevpm9va9d10ZjoDHQGGgMNAYaA42BxkBjoDHQGGgMqAz0qkU3DLpp1uLO510wfD96FVD8+neV0Dx7sp3mnJTsLw5OYXbl3GBAj2RyACuBQyxpo78nB32rABIAZGSF8ZKkXttAcpyZuAE+fHMSQpKVYRiKIKmnH9fN4JmY3QAZ4fz3ZQDW99OWAnvUw2/JmEafjzb8vLrpfnzcV/tPhgCDzw/Put3tTajd+aoZlCA4Z9/xeR2yGuDO2+OO/aUBgR1+S4ab8jFZKDGTXl/85XQitx7vJF1tiR+kCPZJPyYLtwl6EQNAIoDwDD2BC30NGf6mDQju/iQ2AQhAKeFSy9pd+K6r7sExiPVOtvpJXGnuLXFK9vndy/CaAUssdYo6TqDHvY2D8vrDl7RuNLlK7WEwfCgAmBwAATA8EOxHflTQF89RJ8HSrEorgylo6W4lSGbJwVE/91qin5QWgIG5PHgOVAMl/TCH3/hCTxuOYNSym0uM4ACp3RbcAKVkAXOskza0irYpudYMEIvGZodY2S2SysRwKOmwLq6Hi3lYSqyyhiyyhKXnHAkrYP3KMTGIUuSnt8QawGj6CBTshwq8//SNFYmmsjABRNJsx5NykUlKpiu1RQRJsCstw3WUphJbegeb4EHKQTJZjbQA/O8OmZSgKKlfKk0ltiRh71Fa1lh8FgGUYMgcJZJLuwVMyWcRQAmmFHzOXlqT60z9lS+Kz/l1pbgFdXUeyyFRE+dXFV7CJZ0awGBYVGIZP94QPW8KaVsyrwWY/ok0lzwy6mmHlZC1AFeC3OfDWgCyvBHoWstcc7q0cslYFh8T8d5TPOk9vIxLdzV/VEkUI9MALjcizcW5B2AAd/r1T7f39FExWK6UNwm+hnBgvCA9u9HKRlwylseX65u8FwZuAe3yDX7m2/+EAAAAAElFTkSuQmCC",
      ],
      [
        "Shiva",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAADF0lEQVRoBe2Wv24UMRDGvQgKKpoUeYQUoUGCItBQ0tEE8QZUSEg8SioQD4BCk44yVWhokO6KewQKGirKxZ+9n292bXMzXtJ5pTt7x+OZnz//W+f60xXoCnQFugJdga5AV6Ar0BXoCnQFugJVBYZqS71hrDcdbDHns3YYh7cT389vLpEen+Vkvh1PSDC1jxfhzZTzTh5ZYSEcEpfgEGJqC4OYYBWRMxc7oIRDuKhKFjjZPegaSDMgkoU52n4MUC/GyyJksns/+KflkA/lnxYzIKIh2fGP9wHs6/AqT+BVpR1+rXAIbFqwE8nozm9itbb+JsdQcP19eYpXc74mBXefHrmrd/ckRqwX1iP84N/63G3tiH5Xr7+H7i8/P87CsC1rMBrMkvv44+73n5Rmt92k+rJycvowmU4e3EfdnK9FwcEnC+ueoACZAAIQ7AQXdjNc04gCwf4vqQkggLKES6tq+/DONW2SKUBQ8fzZExkv1YV9zSljBkSy+Hv+wTl/L2825TUY7Li34cc+sUyD0FQsCo4ASmfg0WmM722YSm6ItB7hi0f4hf5GSO0mmbL5hKXDOUCKPUC4QCj+eGgL06GqBjAqtwy+BK1BST/U4Xcx7AccCcXo5sj6KUZwQBZuixCSA2A5zxP7yTaA8spc+op3PSA6le5TJJWJ4Vey4ZCO/eGhfjRTXFcNaeQUlt6XKJwBfK5xAy19xLsOENMBVaQCeJdwUsWafX/Vje76jcCoV3VTjOS/tjJKPl2EYknv0rKIoNgY/NE7K6u7R3jWdlzc3XSsKRinVJOHkWalRkGOkuUsQHqhcixTw7qKBlCXgQqy1PU66LUOUMJQOZZILdsPopQdmteGDzdfg+X4PKKa8zR3DIA1qNzenEd3DuYJo2V5/2LHlmy1/gr7ujUoE/A44U0h21bUWwF16w9gUdHlWapGbgVUJ1jr+H8AOb2RZqh+kjXQtuyu2nTJWBofFa51F+drD4ex/MphWnyMykMb9vglLQdC72ppAYxwyu+4kFHeJPgawoYxQlpGU5s2jl7Gsviyfy9vRYG//d7gIG5LWJ8AAAAASUVORK5CYII=",
      ],
      [
        "Hades",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAC90lEQVRoBe1XO27cMBDVGu7S5AiqXFkXMbx3cZczpPMF0qdfwMUCOcV2rnSQIAofxccdieRqhlp3JLAmOd/HN/zIXddaY6Ax0BhoDDQGGgONgcZAY6Ax0BhoDBQZOBQ1ZcVUVm1qzPmsDtNHwPB5uLo+TSnmnP5l9r06bq6n6x4UNokJkwNYDhwcpI72SSCFwAyQyQgssJKkopx29EsMNwRmgIx3DiX++/nQEQx1mEOORjs/qfhTDfD3928e2OPTv2xayAEUdnuaacOGRNN7YI/luwWApX2bD5I5XxWDf15fu1/PzwmudalhADvY17bHWkf4/RgG7/7zcknCUJcojAIz5S7+dDweY5pxHON4Pej7PopOpxPGNfliDMsANzOATsMw+B5z/gpyS/xou3dFkU0wCcbYI8M9WKs6JGF5/n0rlVjI03cw8rM9sAKMZXxzVw3e5UvmgCAt5NDDzrXoh4mlWQD6DwXegX3IAhAoJcqLhh5zflTM0s7Pg8zEqPaaiUFzlzMSv8ynFBgjOD8Rf/ylnfnyESbJUAPQM7cOvgZKxtYZpB3GfjFzyaWp3wdSwLG6xAgOkLnXAsH4pLFnAvbwkzoA5XahTa5XA4Rz7j1FUpkYdjmZEx+CP0zUTVPiImvIIkuYm6+RsAJnt7B+rczMVQBRDrAiGcBcgsOcLZFfDwaNpverjG7ZXlViJB+X7km5CIo9zXPbwukAVP5onvRcUaIQgnjFBBl94j9QkJcYDCWljwirG2oYlCstJiJz7HXpt600ALejOAsyyF7lpDDaBVCCIXPskVvqFViyJrsASjCIvjXPItgQFvfUhh/U68Nzy6U6j+oeLGVev784sTlZyV8j31VimYDXCV8KqdszrgW4uANvAQiMWrbDIlwtwEWQr5zcBSDLG4Ae7lnmmtNVKpeMpbFREW89xcnew2Usv3KYFR+j63vRMQvgciE0L/YWgB7c2SXui+GWCvmSjE714T6xrCAtqymVjahkLIst/Vv/JQz8B36a80W3YbY3AAAAAElFTkSuQmCC",
      ],
      [
        "Thanos",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAADJ0lEQVRoBe1YPW8UMRD1Aj1CKKSgoEeiSUMZUYKUEqgpkbiSgl/AD7iCMhIdoYwU6NCVNKFAQpRQUFwQoLSRok2e18+as9e5GW/ovFIys/P5/GyvnTjXnsZAY6Ax0BhoDDQGGgONgcZAY6Ax0BgoMtAVPWVHX3at9Zj7WRP6g9mA78P8fUSztX0/6lQOF5+puoezx15/NPftTD2vxCoGheAAbAwcSkkf4w0tYqgZIJsR2LPFnVhMKrQzjnkyRqObAbqNoezH7wde6fveEYxsSDvjmCdjNLodYKi6OHnpgXVdvqQAmHbE1YJDq7z6+mH1s409H7V1N98cafrht2GzzH8/gcvcr4rBHydf3PHpUYpldKoRh/ja51ptIvI+fd336Q/u7WRl6MscRoOZ8vP6/c71V7HNjau3o54q/05/RdP+8Wvo5n7mhNDRf60BFAABJADw7oK9qldVUgAJEdkkUEo4a1lDLp+qTRKSPYulKRb24WxkR6O0AkQz//N0843b3f7p3v59MdoSdvgRx5wgR+NLRgvAHg1nbvgG3lre9DVhw1RyQ3A9wo5HxgWbiVHtZyYW9WfrwveOv9BYHncEFwOCIm84qa/0rgHomUuL8xLAwiVQckDQd50fTBxwyC9uVvUUozhASqYIDpIDoJQ+6MiTPgyIyyWNle8aBmP83MXzNDIgmzKQtoTl7jy/B4OWp0itKBLBBBty/LSLmAvVwLrPYyB2NzaQGDRdK1I1xbjmp9NBllgNtxb+0AaZxAGkJ+Xd8jnByfBMVwHEbfho849MxnTJd8erFyWdBYYIlJLhmVStQd9kmeWuGHjvg0xBrgQaXzQMcpSUoy0IinI0qMKoAagqKxlUJSiDJgGUG4DMUaK/9CvxZGGYttpH9akRn5iqPpMAGjpW91Ht4hKQ9PwFW2O2Ur7GPmkNygacyiCla5JeC1C1/oAsMJoel2rQtQDVDaYGXgpATm8A013mNNfsrtJ0yVqaGBW51l2crT18jNOLAzrj9pPcB3FpBXA5kLUgLQA9OPw7jX8IrasuTxLchrBhrCAtoylNG3HKWpZY5jf5Xxg4A33NJeRrlDYyAAAAAElFTkSuQmCC",
      ],
    ],

    //10
    [
      [
        "Crimson Red",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAq0lEQVRoBe3QwQnCMBSA4XgXRacQz13BDVzDaVzDDVyhZ3EKRfGutJBH6aWaXip8PaUhefn5UvIRIECAwKQFZmPq7vvde+j+6nQe9UbR5Rx2fb6G+tJmMW/PlIb+HNjE5bD69ojAQ32JWcdqG7LVetmeaUJLImNovPTFYtKC3f4c2t3rr0vU+jP8EyBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBA4P8EPlmNJAYt2mjTAAAAAElFTkSuQmCC",
      ],
      [
        "Titanium Blue",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAArUlEQVRoBe3QXQpAQBSG4VFWYAtSdmILNqEsRdmELViGuynZgWyBqDMXTI2OEvW6GfNz5nzzGMOHAAIIIPBpgehJumpc11B9m0WPeqiKJdgy2VA+k6T5cUYbNA52OB3Yw0mw2Q5ut69L99ii6S6ye50mpLvUdbrx86agKqC8QYLK3Ddq1Hz3sIYAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAgj8S2ADEr4mh5zIR5cAAAAASUVORK5CYII=",
      ],
      [
        "Gold",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAn0lEQVRoBe3QMQqAIBSAYZVGx7pC1+msXacr1OgoGgk+pKXSxeBvMtHnz6cUHwIIIIBA1wK6pc5vJj7dH+bQ9EbV5Rym9/DUp+Jk0pna0M+BV1wOi4eVwGFxMsuvVmT16NKZK7QmUobKSy8WXQuW/Tm03Luva9TuM/hHAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEE/idwAhntJAbTGGghAAAAAElFTkSuQmCC",
      ],
      [
        "Bronze",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAn0lEQVRoBe3QPQqDMBiA4XgGt1J6A0/VoR7JDj1VbyDSrWewBJGvuIhxUXgyJSE/L09KBgECBAgcWqDaU/d5VuPa/ctj3PVH0eU5bPiu5aV0raczpaGbA3PcHPbuI/DehdSrDdnmNp3JoSWRmwPzd4cWDLMI/d9bzkvUlm9YEyBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBA4HwCPwSnIAbqm/JNAAAAAElFTkSuQmCC",
      ],
    ],

    //12
    [
      [
        "Crown",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABSElEQVRoBe2UMQ7CMAxFDWWpYOQA3ICzcwgOwMrEDmMrllbBNgGFkLaktRBCPxJKmgTn9bkxERoMwAAMwAAM/JIBZw0zNwzomqNGM4W0BKTibPi6PpQpoD0e0cwoqGsOy2eoxbaWsUlsM4NFxVAnIu2fqNMHZoDTUdIRxgDGt1TT216WVKxrkt6n+21fGqF/NhcwWUritMbPjODcXkFi6H46Xs0FjEvJy+UIT+uwGG75aJwNqCnc6Y11DfcJW3qwzMs6N933EU1i0yIxNzgl35qkrF3xjzzkhscl/5XnqJI1huPxPbVadgbjpjbkAkpt0+9IALjeaa3jdDoqPQT3Ah2uBZaza2N2ivWmBnDy1gpz9YWa+wfcY01tysM3mtrqOGjsWkc4TMMADMAADMAADMAADMAADMAADMAADMAADMAADMAADPy3gRsmeWod4urohQAAAABJRU5ErkJggg==",
      ],
      [
        "White Hair",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAArklEQVRoBe3QMQqDMBjF8VRcXCr0AEInPYH3nz2BTgUPIOjSMRIhGTKY+grB4e/0GXz5nj9jeBBAAAEEEEAAAQQQQEAXeIhRK+SkXUrIDp8p9Hu+mjDHw7bM4ah/t26+vO9q4Ch3Vio0igZXVilZRvckX325rq5+/rlx/VqfSy749wO3TLlDzRXKspyZ2xfMicEuBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAgawCOxHGGwZtl1dfAAAAAElFTkSuQmCC",
      ],
      [
        "Gold Laurel",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAAy0lEQVRoBe3RvQrCMBSG4ZO6ioM4C04iOLt41V6Ei1fgzyA4i6CIXVqOTYa0OOUc17fT15DTL3kqwoMAAggggAACCCCAAAJ+geAcVcecq8szpIfrKZ9vMp3n/Btej1te2iyWMXv68jdKQjycNudK273o8VmbcldglrfeSJvdWMLsnS6jd1sebdOYqbMqYRvsCbL6pNeuzJQv6zrOmQ436C2P8beW7+53euesgn0jCQEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQACB/wS+UihYkLlpMpgAAAAASUVORK5CYII=",
      ],
      [
        "Trojan Helmet",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABiUlEQVRoBe2Vv07DMBDGnZYJVUIgeBOERJlh7cL7IN6HhRVmioS6I/EKIBBSx5bDZ2LXIXHiuyaI4cuQxL5/n3+OL8bgAgEQAAEQAAEQAAEQGJBA0Vfux4spLd4/zfHBnjm9m/eWd9SHwI/Lc4rz/B7HNul7LwKlRSX+2wpkcrR/c1+pWY6drWJQDLTfitvS1e3EFIfLUPbpempOruZhTG8TszMLdlUtTRB5YXS02YDi9cuwIBbcNF8KFdeTBtTEeWFWQMhlF0Cx0MiH6Qa/gLrlReRs89D6wd4suahoMkcslP3HZ05J0r9FZ7aJVi8jplhpK13R7M9x1k8U15W3yS4W55OUi/oDgT8kfN3sp5bg5hhml1I6Pu8qA+Vh/nvKjtTS4wJqgmXRTpG5fqlEKoHcMvjqOs3e7v1TItrmVQLdH8OK5GZs+2LjyeR5tvt+2SZiCJvraVF/q9XgrY1aS+MiakEDTCQPzDYHYwCdSAkCIAACIAACIAACIAACIAACIAACIAAC/5HAN1tiqt/qNY7MAAAAAElFTkSuQmCC",
      ],
      [
        "Helmet Horns",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABSElEQVRoBe2TMRKCMBBFg0PD6CGw0dJKr+FZvYZWltrIIXRomNFsyGaCA2TXwUZ/GkjY/Ly8EGPQYAAGYAAGfsLAc+JdiPNmgoWftlGZODSRqcqTACbW++7nFCDvdnIK6amkAB3YqbpOCqjJEwFOSqcMy5X1Q+V9FygbKtaMiwGPt4vZLdcEEi/swJrzvF2zsp/KljXfPBi6U085mhZPHprnLgr/NxYy1DWHRQtU1MbURRg33LfA+f4exhluW65Mlrmlk+snC3x6uM0UHMB4aQYa6ntQf3PFcBT32SXxx+h4CK6vxeNxfV/tyJgU0IrL3M6dPQ6MIfidn1QTvdM8zrBfpCenMjgeSv+gPcrOv8gb6T7Hc7q18p34eXwz32JUXRWgKhnFMAADMAADMAADMAADMAADMAADMAADMAADMAADMAADMPBPBl4mblszAJ+RgQAAAABJRU5ErkJggg==",
      ],
    ],

    //14
    [
      [
        "Gold Trident",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABfUlEQVRoBe2ZsU7DMBCGL3TMClIlNt4C8Q5deAV4qvIKDDCyI1ZYmACJoRISLIDYWplcYkdn05DoTC+i+j3kzrUv/vrZUaWUCO3/GnBD0HeGTNrAHHfztODb9kKOBTj4O1sCRrY+P95TyGg8DFoB9m1p57gFoLu6vQ9C2vj8+NDmIfHzIpMWgPX6hwf7HIsAk8SCx9dBmwCuWzgB7OyaACaru+VFSSfTGXGsWrSlyVwyA5yfX9Yw7pposvtFq70mcr9qzo/XHXnpOhNyzl/kLQCbY7jQJq9EZy81PJ0ez/jjiCnqhKINxXorvbHGYAXHrThqIqdt5hOzLfaLFwyzeiuJzXH0cAz2Ay6Ftey75V3JRn99QBjI0qBKAABV2kQRDAoZqhQGVdpEEQwKGaoUBlXaRBEMChmqFAZV2kQRDAoZqhQGVdpEEQwKGUhhAAa2yYCrXiLh1YfJjuKXJFczDMJgroHcepxBGMw1kFuPM5hrcMz63n+ZxoTbnrW/AbQKVAVEsSQ/AAAAAElFTkSuQmCC",
      ],
      [
        "Silver Trident",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABZElEQVRoBe2ZMQrCQBBFN95AEMTKQisr8RCWNp7BU3kGG0sPIVZWWliJIHiE6IRMmN0YE2ZxgvLTzCS7k32+nURQ53D8roG0CXqnyaQvzEn3twfdthayLcDGn9kS0LN1v15DSG+cB60A67a0ctwCMN0djiykiJfzqcg5yed5Ji0As/Vn/S7FhGGCmND4O2gTwHcLB4CVpyaAwerperN1w9HYUXwd3pYGc50ZIMNQnxFcbzDIIvddPh7yVfZEaWLkhcwa3YPh+H70uuEWWC0XdNnrU++Ei74Us63kJ5oM8rtwPp3wkiUesy3OzSQEQ8bYXA5HYCU4pm4j0ouZjH58QAjM0qBKBABV2kQRDAoZqhQGVdpEEQwKGaoUBlXaRBEMChmqFAZV2kQRDAoZqhQGVdpEEQwKGUhhAAb+yQB++jDbTXyTxKqGQRiMNRBbjx6EwVgDsfXowViDbdbX/svUJtz/rP0Eaf9b1XtdvckAAAAASUVORK5CYII=",
      ],
      [
        "Lightning Bolt",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABYElEQVRoBe2Yyw3CMAyG08IFiSOswBJMzRAswQpwBHEBQh2I1Yft9gJ/QI4EzaNSPj47TUoIXtyAG3ADbsANuAE34AbcgBuYZCA2d9GnU+pOC9eIt91SnL0UwFCtzmUDxrXsSu4VfwumswRANf9ISQmAav4VA6jlXzGABKIVdIg5/+abBzFWfVA0oJl/BAsHTPl3XfTFcRsOyCRKBQnI+VedLwoeOMR5/51tE99ggVAv0mAYyz8kIIc3uTO+YAZzeA22NAQDnBJeIoQBZnOtFSwe+fN9iGsGivd9iLdDndsdFqRBeqykR8tPnGaqYzosdOyV0lDDS4BzIOXgHVhiQQKGZnG8dhOJ7N2HXCSMZeUfFDCv3mIPC6zQqKAM8mHBCi9xowD5XcQKLxQw558R3TQEM0izj4V3DP6T4+bu0Z4YarANotVhgFPDCwOMJ/kvX83kt/vFw+m3IXw+N/AXBp5zLFDRhIeqrwAAAABJRU5ErkJggg==",
      ],
      [
        "Gold Sword",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABFElEQVRoBe3WMQ6CMBQG4AeuJjro7KDncfEMnsozOOgdvITRwVkHTRyByutggLSPlwgtJj+T9L20vx9pUyI8EIAABCAAAY+A8YzXhtPaW7gXk5/sYq0hYwUkM9ctrevqSTY7jHlmUTFqwGT2bv3rUQO2pisbEFCjJPVAUNLR1CCoUZJ6ICjpaGoQ1ChJPRCUdDQ1CEpK5mHvg1JLtJrJzilfVMXLKqfDJ/71G0HwbwWTe6HKnqi6um9q7l5vDm+h+0x2RrPbH2mxXNF0MqLnK6fb9ULbzZqLzizOwZ7C8bRNuepSobNU18ZvCAxOgHfzYC8L36OGj5zykXa2++wJ4F0NheMlADiWgAAEIAABCEAAAh6BD+UaKtJGYFqEAAAAAElFTkSuQmCC",
      ],
      [
        "Silver Sword",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABEElEQVRoBe2YMQrCMBRAox5AB5dODnoeF8/gqTyDi6OHECcnHZyKIKgHkMoXkbY03w/W/govS5v8T/J4aULSECgYwAAGMICBiIEs0l5o7hZqzVWy9XYno32E9AIMwyQx6XADFLrFciUP1aIr4Gg8EUC1uAKqZK8ggBZLWg4GNTuWGAYtlrQcDGp2LDEMWixpORjU7FhiGNQsHQ97LewayzanixxU1cOqEDLF384TBv/W4DlNTewdU1b9SeXVG+WIBupnevaYyV1YrpuDfi9cb/cge+F8NpVgJUtl44/gpNuyufxQTbPkx+YdA60zIKu5tYeF91Zj+f3mtbTz240XQ+s+K4AwgAEMYAADGMCAg4EHFkEsf2TqxyUAAAAASUVORK5CYII=",
      ],
      [
        "Torch",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAA80lEQVRoBe2VOxLCIBQAn5qLWHkD76B38aIewBkrKytbWoOBGeKEAUIBhGLTPHgwsCyfiPBhAAMYwAAGMIABDGAAAxjAAAYw0NyAvojOmXSf06l0n1w4M+8mgG7BOaDNAS3UzSGKrEE2BVzAOMgpLvJ/dlvaefWqVd/edzphBxnFxOE6BlmCyYqUqZsbZBkqwgSHVkrN+cfnbcvn42nO+YUgtd+pcF0bSA9uC47ksvT99TTbndpyO0DTW5xEjjQCGBHTfXr17LkVdL/FDpSIgcIGeKgLC40P1/0z0z1g3G39luy/SX0UZsAABjCAAQxgIGbgB42vM1Qvk90cAAAAAElFTkSuQmCC",
      ],
      [
        "Gold Spear",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABHUlEQVRoBe3ZMQ6CMBjF8aIsREbP4CU8hGf1EF7CK+hIwoJWW1O29t8YbDF5LlXfB77+gg5ojB4SkIAEvhWwOQducoZ+MGOnq/9oLFmrYPaem+zJ5QaDnj9je3i6NdqjmmBz88Vw26ULej1Xzt5741a6FksX9KVcufY0zCWRseCAnc69++bax8X4NbyOdYhenLEDFnjflfvo7QezPfoz1uiR3MosmJx6h8WvwVDI9rvwNLlWK2i6MVkshPUKhgawqiAAYSxBJIIBCQIQxhJEIhiQIABhLEEkggEJAhDGEkQiGJAgACmWgAT+VcDdhvM3j2gD+h0kIcolSEKUS5CEKJcgCVEuQRKiXIIkRLkEo0JjF43WEuC/7Wsp+t89Xo2rP2rwiyeDAAAAAElFTkSuQmCC",
      ],
      [
        "Silver Spear",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABNklEQVRoBe3ZMQrCMBQG4OoNBEE6OejkJB7C0cUzeCrP4OLoIcTJSQenIggeofoCKW9J//CwScHfJdGXl/75rA5aFHxQgAIUsArUMY3DmEUdrKnPz7dsC0PmChh95kH0yt8t9Hpux9VkJGMwRzbBV1VFHTl1QKcn4R73WyEjuhdTB3ShJNxuu2lCRlEmWlTvD0f55Nany9WN/nno+sGbM9Twg9clnNObzubFermQLXPkaD1KI9i66ltMfg/6QOOy9NPWMVvA1lSqyIAKwzSloIlNNVFQYZimFDSxqSYKKgzTlIImNtVEQYVhmlLQxKaaKKgwTNPeC5pOxSYKUKB7AfkZzv14hC7V+68ZBkRvIapTEAmhOgWREKpTEAmhOgWREKpTEAmheu8F0QG6rMN/27u8+P/s/QGgaEhIMskxCwAAAABJRU5ErkJggg==",
      ],
      [
        "Bow and Arrow",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABv0lEQVRoBe2YO1LDMBBApUxKmBQQjsBdqDgJp+EStFSZgZqGoaCFhp5AkSFlQLACySt5lUhCzrrYFPHG+vj56R+l5CMGxIAYEANiQAyIATEgBsSAGBjUgNlW+2Rb4h7SzOb6AB6ThOQGVPp4bT3cPj6QkOyAZv6LMJsdkg3GDkhSoZucgLb/TU+/AEevVh8Iqws5AX3/A5z312VHNZLIbJ4nMDD84Li6WfjYMbIadBDuenQyd6G/jgqQGslcgMEA8bqIgAswGCAEl79VDHj/8tTryL62gsBN0LuKFAG2gtsF9e/0i7NuaqisrDfFQD2UgCKDlTDZxajVpArwcqF0A4tZ4FWAUPM+IbPeJJWppcnUnjD17Oz7rSAHA4Q3aQFJjeJsSzkZCyDJyX5wwAKTfICZkNkTdU7LVeXBzQ1xtBnlB8QmAS7qX+bzzi6XQVNHearEFBfCJlFh2A8CHD8ggorDXjNT82D1Uhc/rcXvsZ3sAoPRIPLvy2pQL+2h3cJQJzpIYAU0b/afLQtInei4AfX0fK1+Du/AEYxmS/z3xWoQg6RidkDXD6ntPkCzA7p+OLYpBrdob0XBiRKLAW4D3+DRswhk7EuOAAAAAElFTkSuQmCC",
      ],
      [
        "Gold Staff",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAA9klEQVRoBe3ZwQkCMRCF4cleFU8WYQ1bgH1ZkkWIYAm24NXjakyyLCzIhIFAEuXPZcwwYR/fBgQVYSGAAAIIdC3gGqXzq+dmMwyrwVof/XTeyusiEmtY67BfGWoH9NN9ELd/yu00phr3uZC1A4p7vFO4w24zhwz7nlYU9OH1+utxTDXuc4Itwsc7OIcLtbdwC0iStISrfgeXhNZKQKuUNoegJmPtI2iV0uYQ1GSsfQStUtocgpqMtY+gVUqbQ1CTsfYRtEppcwhqMvQRQODHBfjpo9oL5JuklBpBBEsFSs9zBxEsFSg9zx0sFWx5Pvs3bMtg//XsDyLmPTBKIeRSAAAAAElFTkSuQmCC",
      ],
      [
        "Silver Staff",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABAElEQVRoBe3ZMQoCMRCF4dFW9AoWWngGD+BJPIOX8Qw2ll5AsFi0EbaytvII0QksLMiEgUCyyp9mzDBhH98GBBVhIYAAAggMWmBUKV3oPTeZYdwbLPUx7A9HOV3vovWz+mG/MpQOGC6PVuaLpUx321h1nwpZOqDcmjaGW80msep+SEsFw+f1hvNmHavuU4I1wusdjOG0Di1cBxKa58sVrvgd7BJ6KwG9UtYcgpaMt4+gV8qaQ9CS8fYR9EpZcwhaMt4+gl4paw5BS8bbR9ArZc0haMnQRwCBHxfgp49iL5BvklxqBBHMFcg9zx1EMFcg9zx3MFew5vnk37A1g/3Xs9/TMELsirxysgAAAABJRU5ErkJggg==",
      ],
      [
        "Gold Axe",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABVklEQVRoBe2YQQrCMBBFp8WVuNQrCJ7Gs3oIzyB4BV2KKzU61ak602QM1kDxZ1My+UleX5uCEqHBAAzAAAzAAAz8g4Hw4U2aXP3hxG9i4bSa8Hy9uel35UoAUjU9kNo8nLbN1gLZ3ATndCsCGGb1GyTDVbsLCSTDMxzndKt04Qd9sdVAhf0DRl8fcKP5hRFaLov8A0JZUkwyJC2O1MJ2mJM5RQH5sQoUbcb3x8omb/VYKwYocKPl/V2Td67pO5Ax+L7q4bwmPqV8Yp+ndlu/92/jnHvJ9LW/u46G4wl8cDRMV85dvK+AmJP1ugB5TOeo1DvYfjaEMHI1uVKAER6/DEDfUToBg2k//igM+o7SCRhM+/FHYdB3lE7AYNoPRmEABgZrIPabxNwQvoNGSWYBBjOFmTgMGiWZBRjMFGbiMGiUZBZgMFOYicOgUTKggvm7d0DsA0K9AmFohYNiF8A+AAAAAElFTkSuQmCC",
      ],
    ],

    //15
    [
      [
        "Armor",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAB+klEQVRoBe2XO27DMAyGqSRLYI/p3hv0AD1Ez5pD5ABdO3lvxhhZnKj86UiWVdcPySgKlAQCWRJNUp8kmiFSUQJKQAkoASWgBJSAElACSkAJKAEloASUgBJQAkpACSiBXybQHAt7O5Edc4t56I3pTM1tphSm5puPzWAAP41P2YvnswOk657iYKTP42vILtWIOdRkn3h9V7bAwdxOtbVlQebC44/gMG+o7rlo3gu7e6lNb3Ckk0xQggsM23MhPde6qVgPC1giswjisINOvHLzeSd7HnBXtWPmwPOgHIg9l9y7BCPjj7NRx2aaY2npubsfsrVui7n1UhnavV2S/fSX563OebBy3qApwQVb3N/GbhFzrMY6ySuDoZDiIMGKmN78CxEHh34Gwc5cTDCY6R4Tn7ICNIf2sEt64bQDQfpx4uZdP6XNCtA5jAn2z6DTSmtnpZkp00KQE7IlTtRMEP21JIugS8otQeQ34rxY+tvt5tcK9k/aWTfNgB5fHL/FmUkaxHK22H9J3BZLcMEWP740WZk6lSAKUdryhbjzKuXcPVIOVu36WP2NvzCcrDGc5CvpJcQAjwsl1ddCN6reJ7AYOypi2qOMbgU14fb1+/mSGjKsBbnKjutJZ2OsXXSL/b84lPT8awvWNkHHTuSicPDQkx8r+PdjZe3/ZwJf3SjOwCJvx9EAAAAASUVORK5CYII=",
      ],
      [
        "White-Gold Toga",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAA+klEQVRoBe2UQQ6CMBBFR0NJjK45gve/hCdhx4YNLiAx6JSIRKANaJoS3ixI209nft60FSEgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAgIIH2FXVdtwFLLiulBjWiNdnZ675RmlRTw9i1yeOy0/f5uygKaZqmX0jTVKIjmee5vSjDduu4dx3DAJP/6sIUyU2cyU2Y/KVLh7Wb25vY2/q4nLsUp/tsquQqq+vMJvUJVVV9vy6jubZXz6Yvl0tPXKJLK8vSysYY0Ud6KnQ9y7IpKdyaEvLRDOfGUcll1LEtrDRnMqwLTzU1qZfjHdG9gx7/yBCAwO4IPAFgr3styyF+UQAAAABJRU5ErkJggg==",
      ],
      [
        "Black-Gold Toga",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABW0lEQVRoBe2Wv64BQRSHx41GiCiIcDUKWkqd5r6A2mN4JrUX0CgkWrVC40+EQuTe8mY56x6ZjCV7z9md6rfNWMPvfPOd2cEYXDAAAzAAAzAAAzAAAzAAAzAAAzAAAzAAAzAAAzAAAx4NfA2GQafXD3yU/JAWqdQaxgekGJAW5gNSBHjcbx7i04bMPCr98wW1l+D4IujlYibO4xx3FBmkkNNhZ3yYVK34s9kKytV6uBftlU8nY1WunaUOShtSDUirTRNSvAftNmzXq4y7J2k+iXMyEYMMG2VS+3RnOTyJkUzecsKfQD6CeJTmiw0G8zvIbyF/r537ecmQbRtxHbHB7qj/dLy4hNRe2pvGrNyp2PdiQCr8fTmbQrH0EpTbe2t9bCD3g2LAv/0WHjHvQBnSLRz3XgzIBWxQek8LxLk8qgE5KOoJ5jnNmBggQURB2n8oNKD4LgzAAAykZOAKsFpnWVkmlBEAAAAASUVORK5CYII=",
      ],
      [
        "Purple-Gold Toga",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABXElEQVRoBe2WS0oDQRCGKw8MMSLuEpDgQvFIIngFyUY3OUFW2YS5gpvcI7fQhYigOxFcKISRP1KhGWfyqOrp1d+bntCZqq++7upEhIMGaIAGaIAGaIAGaIAGaIAGaIAGaIAGaIAGaIAGaCChgdnFPL8bTvIUKZvWJGedc0kBaQZEYSkgTYDP309r8XVDNtaZ9nzA9gJOB6CnL2NzPI1TnE0GEeTt51VSmHRVfNO/zQcHp6uzGFY+erxyxQ1juQPVDekGRLV1QprPYLgND+9Zo3gmsR7jnoxiUGHLTHq7O4pBBSwzGV5F+r19ZrPBfCGr3+LlUe8vX/erMm/7Usx52pVRtyzcX0/+XS/FV7C9OJsiWXFp589mQCT+XH7IceukEtS7vajCrF4VoDEOW72NoJ6L22xQAdEYeAYo5hjWEEdHtC4u62BN4pmjAQKiDDL8Q+EB5bs0QAM0UJOBXw3UbzTQvDYbAAAAAElFTkSuQmCC",
      ],
      [
        "Red-Gold Toga",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABW0lEQVRoBe2WwUpCQRSGjyGRKUlB63YRtHWj+3oCX6OH6Bl8jZ6g1lYLt0LvECgKgghx45eODeNV9Jy5s/pnM/dyved8882ccxXhoAEaoAEaoAEaoAEaoAEaoAEaoAEaoAEaoAEaoAEayGhg2n8oPh57RY6UJ9YkdxdNyQFpBsTCckCaAL/mi434qiFrm0xHXmB7AacD0N3Xd3M8jRPPJoMIMprMJIdJ14oHnfuic9Ven8Vw5Zcvb664YSx3oKoh3YBYbZWQ5jMYbsPTaFyLzySep+iTSQwqbJlJb3UnMaiAZSbDVqS/O2Y2GyyGsv4W/7T+emHjv3nHAPVbMeepx8EOvf987m21l/hdbC/Opsg4fnTwvRkQib+XK7k+O90J6t1erMKsXhWgMG7OG3tBPY3bbFABURi4BijmFNYQR0eyKi6rYE3imZMBAqIMMvxD4QHluzRAAzRQkYFfb+Rv0a9/p4kAAAAASUVORK5CYII=",
      ],
      [
        "Turquoise-Gold Toga",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABW0lEQVRoBe2WvW7CMBSFbyoW1C6wZGKtxExfoG+BxCMgNkZGNrohHqFS36JTt2QuOxMLTIwoxA6OTGQL5d7Y02ExYOee4+/+KET4gAAIgAAIgAAIgAAIgAAIgAAIgAAIgAAIgAAIgAAIRCQw+d0V9LMuYki+cEUm6YBimGQbVBeLYZJlMD+ea/ChTSa1UtsvZQ1qc/fntOnpih/Po88iqGNl/xSDpOzGy1lBH+OqFi0C+edcFteKJQ8U2KTcoLptQJP8GrTSQF/fCTVqUm9vFuJh3g1BY9ZBUtrd3RA0Bh0k7VFkjrVZ2QSLP9Lpu769Vnr9i1e3905snZ436pON5LCuxsvJf1Cn93AsD2z9h57s8FOsmiLbPwzrppZO7yht/t3qNxt9raIaIx0SlUZ89SYZ3HKDxqmjg82WxCA/xUbdrI4ONluStTuDyoXDpP1CITGKZ0EABEAgEIEb/ypksUkXyKwAAAAASUVORK5CYII=",
      ],
      [
        "Blue-Gold Toga",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAABXklEQVRoBe2WTU4CQRBGC5xIiCxkYUxcSEiMV/EGrLgC0aNAXHABV97AA3gLEhMXJMaFLnQhwQz5MEU64ww/VT29+nrTQ5qpevW6q0GEgwZogAZogAZogAZogAZogAZogAZogAZogAZogAZoIKGBq9Fjfjkc5ylSNq1JjrsXkgLSDIjCUkCaABcf8434uiEbm0wHPmB7AacD0K8Pd+Z4Gqc4mwwiyM/7i6Qw6ar4/OY2b53112cxrHx2P3DFDWO5A9UN6QZEtXVCms9guA1vT5NG8UxiPcY9GcWgwpaZ9HZ3FIMKWGYyvIr0e4fMZoP5s6x/i387J3/52t+VebNrMefJKqPuWOhNx/+ul+Ir2F6cTZFJcWnvz2ZAJF5+fUrWOa0E9W4vqjCrVwVojKN2dyuo5+I2G1RANAaeAYo5hjXE0RGti8s6WJN45miAgCiDDP9QeED5Lg3QAA3UZGAFjlJuwa1YgFQAAAAASUVORK5CYII=",
      ],
      [
        "Icarus Wings",
        "iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAADMElEQVRoBe1WO44UMRB1LxOhWUGwJESQDCeAhENwVg5BAgdATAIRyW4A2hHRsI2f18+U7Wq7uoUESC5pxu1yfZ5f+efckMHAYGAwMBgYDAwGBgODgcHAYGAwMBgYDAwG/lkGJgXZrOg0O8VslcqUp0w8v//8qcry6vkL6Erbym6FwpxHJg1Oh6unVZ7jzVf3B0FuzjN/u72dNYHeM4uSaGWpJtRQhDitPK0cGrakEyAb+dtDmOQSOCYqAV7EkIH2Mvw0Te7Dl2NQP9rvy+FNfcZBXMQvJe6BVCkCLO2CM4xfPjuEMQaLpa7sewr6MQ7iIj77S/67pQGpRxAE4wZCmeLGqSmQjv4bwOiHIYLyJS0s9S4YXNxVuotzVnDw97t/gr1VMBlMwkuaQbVwMYiZU9iHF+XnOzefjxcpCPWyxTjspA5xfZ+hQx7ZxwAqBB38TCX2PlgrWTnnJxdud7jLdAgoBeP3k7hLajAKEEnR+egCjLgqID1wzGu1o73WZiX2BmV5NZ/NOm1ZlGWXJV48ZjYjWO/YLLcJoNwQa9aPxEq/6fr3epTjS9/dNQjHB6/xklkXWEsIkOVm83ZY34ssmhiUyXj1SZ3lm1cbmbT4wGYtwDk+u6zxaZcY+n46hUNQPhpopLUqQHk1CSckQTmqI0fYaJ/BjxPDrQKQjy8vNVtVlx0zKIEU75FOe9V7vTLFYx4eK2UfoSsGt64xBDu/3adSot8TMAnBE8yDXDTPGPRWnIi8E9XEEhCPInn3yvEiO+JlF4K8+8kofVSApRGNZUswBIdbQj4Q4rg6uRgn5fZ9jZi6xHAE9dYnEljCwwHCQxh9wV5zU3HThADKX7YGuSbgFHddM3gAdXUKwAAOBzra8PN6g0zIQzKYX/plAGloBcdA880+3jb3tw76QlolhlkAiQ/mxzclAyiAdZnj+mOgTtsF6f0TUBkrAdx6vBRspdjU+4lAuhOmY4kDjthJPNnNgcQmcLs3p8qvN05ASlvhSSe7Yvw3VBkezhxrhN9NUOWLmLu3dMIa5fHDsRXP/4SH70E7uI8P3WQ7QtK5CIBYk+fjj9kI0oSHEx/tf83AL/KF97eefeZ9AAAAAElFTkSuQmCC",
      ],
    ],
  ];

  //setting contract addresss
  //set god in traits
  // set temple in god

  const traitsContract = traits.attach(traits.address);

  const setGodTx = await traitsContract.setGod(god.address);
  await setGodTx.wait();
  console.log("God has been set for traits, tx hash: " + setGodTx.hash);

  const godContract = god.attach(god.address);

  const setTempleTx = await godContract.setTemple(temple.address);
  await setTempleTx.wait();
  console.log("Temple has been set for god: " + setTempleTx.hash);

  for (let i = 0; i <= indexTrait.length - 1; i++) {
    const tx = await traitsContract.uploadTraits(
      indexTrait[i],
      traitLen[i],
      encodedTraits[i]
    );
    await tx.wait();
    console.log(i);
    console.log("This is the transaction hash:" + tx.hash);
  }

  /* const upload = await traits.deploy(0, [0,1,2,3], [["Black","iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAACtklEQVRoBe1YMU4dMRD1opRJgSggBUUk6IP0r0DJLThWbpGSK3wJepBSUEAKRJH0m/+M3+qtZe/3zIooimwJjT2e8Ty/8dj7CaG3zkBnoDPQGegMdAY6A52BzkBn4D9mYFixt9Hg647jdRw3Z58jvq9fTqK8+/EcHl9+hdOjT0F1mNw+PEG4YnmcxuvLiwBABILotUa7bze3MDHHO6gtvKRn0CUbzmETsPc2F0AEaw3aalfbgBsgzltLa7WrreUGeLU5r60507fazZxk4AYoa7xr1wXQkjacQYt9vlsXQKQNgfcVAOfXpNl8L6Udxldk6T4EOFwx6f6DmyuWy0nSEF+U0oUNgGteEMZwpZjOlExlbUz935BI7fR3fPhx6u/e5hFjSNroPHVWkJYUz9JJ1pheOWsBZxMtt/m+vQ8/X39jqjmuKcUEgwjpfKEbG0DxjzpItfNUswkgA+fMUJ9LbgjMeZsF4MA0MrAGJWhKnSNznk+uD7qQp18CRF1pI9YYqwHmIPKxFVBub0lx9CU7+UIYL815z2FzuSdAuOOmht8lZEzBqU6rODmaYlpSHH+LEB0LhmOAAkiCox6S9yL6Oz9sshmkKcUAoEwhIBv1lNRTLvnSpiQtDA67dMUUl77vlhiUFwQYmtmDsYnBtPiQniv4T43MUU4Tu448byZwWMPCoMZEoFHPm/ZpCF0qEjMwruF2BEAu0iDdcbwMRkxanVCgsku6hg1UTVYB5KpSBHiv8V0Y+P7SxiutRcI4szsR/zDSpuPEqOU46FLmKp6cS9U6TUqn1U5cZl0vg/G3LoNnlYr7MgbBfOnOnCHYM/BUVy1dulaLzR5ob9PWIpmdPSwBlsiYRtQPCeqt7zD8LAAjOFSsFgGDlySPAOaQahSMFaSmpRRDdbW00UbXstjSv8vOwD/JwB9ARSSp6yEcvwAAAABJRU5ErkJggg=="],
  ["White","iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAAC80lEQVRoBe2YzY0UMRCFu9nNgQMCiQMciIJNghCQyGKzQCIEklii4AAHkBCHzYGl8Wf6jV57+8flQQIhlzTjdrl+np9dds8MQ5fOQGegM9AZ6Ax0BjoDnYHOQGfgP2ZgPGNuU8C3OU+r4/Tjw3XGNz56MTxIT3ffPw7fPt0Oj58/HC6S7mfSTUmHXL68pmnK1eI03X1+n5MD5EgAziQunr1qAsnkwwIzJK0R7MRkjX1p0wSQILVJa+1KYOo3A2S/1Uit3VasZoBPrq62Yi70tXYLJ+s0AyQGlbonR+N7vhprAhhZNvZgxF7A1DYBZNlIzGeLJT8Hz1nmlnOQyeVbZErnIefc2nko/fj7/MOnKVcTg3OyUcmdRZ7Vn8cB1gQu+eVbivYs0VILGP2/JSzt6fPl3ZvTc7qbJ/q0svFx6aLAI9TnFwTtN/YYor6WGx17Eylt6EdfHEJ7kHtVyzgnykD4ApQ+J2V6cLva+9v9QwBxxKFkxgtDE8BW7MoeXVQiAEdemQAgJhyYCsMLRmDFfMsr12V0Rtj7rATM40iniWAvsG5X8xwG6ODy8/xeKDYB5TYCsabT2F4b9iv3kzMDcwroegCUfnugfCxyzODHGXcSfpesFYLrvIpnx1DOyBJPOt9I5OcefUDBksChkxR+TLIapFZEsXZbAGwtlfRqy0B7vqWt9yMMjmm58hKnK8xj5Oc9Br/e3AxPX7+VTzV7OIQYTPYEHy0ZMbKIObXS08722df1Nc8RBj0eySadcwys7T0bD7FWJvJ+5HlR0QeOzQBbGcx4vDo597jK+NfB901Z7QcTuTfsse4N1iooAt2ztPT/lLQCXJyJ/GHk4v2Z5ch28FCL1VgMHHXWqnXNp9ZuzRddK4P5t66Sz9eZCoHzMudj/JzfxARR0Byw8mtruTxWjU1VumgVL/YeGWBJjHlGf5GQPlU0wH0iGtpsIwAzOCrUi2AzchrQFsCGpaZgoiAjs9laNmH0WBFb+fe2M/BPMvALccI1g3rNsnYAAAAASUVORK5CYII="],
  ["Tan","iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAACvElEQVRoBe1YO07EMBBNEA1INJyBei9ARUtDsRUSp6BHCNFzCiSqLWhoqbjA1pyBBgnKkGf5RWOv7fVMACFkS2js+T6/iZ0NXddGY6Ax0BhoDDQGGgONgcZAY6Ax8I8Z6GfsbVDEmutYA4en63OH72Rx5OTz+rV7e//oDg/2O6mD8fTmAcJUyxI0fK6uOgAiEFTPDfrtLW/hoq63k0tc0rNoyYc2bAL+1mECiGK1RWv9chswA8TzVjNq/XK5zACXx4tczkBf6xcEiYUZoMjxo1MTQE3b8Axq/OPdmgCibSi87QDQPqfN6nvJ79C9RUr3IcDhivH3H8JMtUwM+mK9KO5xh0JcziZwyGYFGCBhK6mM19T/hkRrp7/7y7NpPr6bB6wh6SPt1GlBaqh3PxD4/iVLXMt249nEiH2w1v5wULWYYFDcF8LUDYDiH3WQ0k/GS5/SXAWQiWJmqI8lAdE/ttesNQCnU8vCsgBBUEob/cWplubifLdorTCmAFFHYBVpsi6zAcYg4nW2cqVB02KXkuyk8lttqVzUaa4ZxOCOmwa+S8iYBCd18hT7QFVNTYvdtwjRyXsPOoACSIKjHyTvRczHOGyyGqSqxQAgmUJBDuopqacsxdInJTUM9mO7XIvHV9hGrhKDq5d1d3H3yJhq9hCgYnD0R/JeFEMON8gcJfWQ3t/FSn3NXLWbKGHwTEa2aWm5nKfgcTILoEy0ZW6uo3kGNzDI0wkj2ErpNgIVCu0zmEyNQ8BWQmL9XcMKMHj+8A8jOeTaMxpc8NJ329wKMHsfxgVTpzr2Ka3NAPGty+L+dcaDgPvS1YR9zjcxkjBpaROxLdcumavGJ86bXGtPcfDsISNYImOygvwhQf14gABcboSmrNQAdOBwQuUhyGYeDXwE4INW48BoQWp2k2sbMcpcGl/GN9kY+JMMfAHFxRmC4LXBggAAAABJRU5ErkJggg=="],
  ["Dark Tan","iVBORw0KGgoAAAANSUhEUgAAACgAAAA8CAYAAAAUufjgAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAKKADAAQAAAABAAAAPAAAAADvhlfuAAACwElEQVRoBe1YO07FMBDMQ/SIloqGEiFR0nIDRMUZOAENouEEnIEKcQNaSiRESUNFizhByBhPNA52nncfIIRsCa293s9k1uu80HVtNAYaA42BxkBjoDHQGGgMNAYaA/+YgcUKz9YbfN15vI79zdlhwLeztRHk8+t79/Ty1u1ub3aqw+bx5R2EK5fHqX+8OuoAiECQvTRot3d6CxNzvrVS4Dk9k87ZcA8PAXvvcAFEstqktXalB3ADxHmrGbV2pVhugEcH26WYib7WLnGShRugxPjRqQugpWw4gxb76dO6AKJsSLysAbi/SpnN91J8wvAWmbsPAQ5XTLz/4ObK5WIwJltI8og7FXI5u8AhmhdggoSlpHK6pv43JEo7/p2f7I/z4d3cYw1JG92nzgrSQn34gcD3L1niWsuNs4kxtcHa+sPBVGKCQfKYCNMwAIp/1EGqnfqrzdzcBJCBpsxQP5UERPvpfs3aAnDsWibWBARBqXu0l67W7dn5+uxuxWYOEHUEVhGmaLIywCmI6bqYuXLDUuIQkuzk4nv3crGos1wz8MEdNw58l5AxBac67eLoaMppKXH4FiE6vfegAyiAJDjaQfJexHzww0NWgzSVGACUKSTkoJ6Seso5X9rkpIXBxVCuUOLhFfYl1hyDt/cv3cX1A32q2YODicHBHsEXkgwxwiBzlNRDRvvgq/qauYVBjYdkvZ43ndNQdCbW6A/pdhx8k47WoJm5O4+XwYBBuxMKdHZOlwFcrbKewWxgNAHfs5BYf9fwAkzuRPzDSIeuI6OW46ChzF08Oue6ddyUSa2duCRTL4PhW5fJ4+uMjYD7MiTB/irfxAjCoAnqJYtSuTRWjc2SNJ/b1i5Ozh5CgCUyphn1hwT11vcw/CwAAzh0qDYBk+ckjwD2UGo0jBWkliWXQ3WlstFGY1ls6d9kY+BPMvAB2zob0Oc9jgIAAAAASUVORK5CYII="]]);
  console.log(upload.address);
*/
}

// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
